### ISSUE TITLE
Support service configuration for local development

### ISSUE THREAD

**Issue by b-abel** [eclipse-hono/hono#2232]
Configuring the components of Hono (protocol adapters, device registry, auth server, dispatch router, message broker, ...) to play nicely together is a non-trivial task. While the Helm chart does a great job in configuring them for Kubernetes, there is no support for local development, like starting a protocol adapter from the IDE. 
The old Docker Swarm deployment scripts could be modified quite easily to start some services locally and connect other components to them. But since the deployment script was removed, there have been quite a few changes. 
The possibility to start Qpid, Hono Auth, and Artemis (and optionally a device registry) with a single command and have the configurations for the other components ready, would help to speed up the feedback loop during development.

**Comment by avgustinmm** [comment]
could you assign that to me?
I'd like to try to provide support for local development mode

**Comment by sophokles73** [comment]
fixed via 966f2f78fe2205ee8ea577bd8694dd16d421a4c3
