### ISSUE TITLE
Allow zero downtime rotation of hono auth secret 

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse-hono/hono#2688]
Hi,

we're operating Eclipse Hono and would like to perform zero-downtime updates on all components in our cluster.

For authentication between the different Eclipse Hono components we use the Hono Auth Service. There we configured a shared secret (HONO_AUTH_SVC_SIGNING_SHARED_SECRET) to be used to for signing the issued tokens. Consuming services (e.g. Command Router / Mongo DB Device Registry) are configured with the same secret.

When changing the shared secret we simultaneously need to restart all instances of the mentioned microservices, which leads to a short downtime. If we would perform a rolling update, the old instances would not validate the issued tokens of instances already running with the new shared secret.

It would be really nice to have a possibility to rotate the secrets without down time.

One option to solve our problem would be the possibility to configure next to the ``HONO_AUTH_VALIDATION_SHARED_SECRET`` another secret (``HONO_AUTH_VALIDATION_SHARED_SECRET_FALLBACK``) which would be tried if the primary fails. Like this we could perform a rolling update of all components without downtime. 

Thanks Chris

**Comment by sophokles73** [comment]
Supporting multiple keys for validation seems reasonable to me. However, IMHO we should also add the possibility to limit their validity period in that case so that old keys won't be used anymore by accident, e.g. if the administrator forgot to remove them from configuration.

**Comment by Christian-Schmid** [comment]
Good point. 

My first idea was actually not to have support for n-keys but just for a primary (= key as of today) and a fallback key (one which is used if validation of the primary fails).

The fallback key would just be configured during the time of rotation of the primary key. 
Like this unnecessary non-success validations could be prevented as well.
One downside of this however is, that it requires require multiple updates. 

With the possibility to limit the validity period one could add a new key and configure an expire date on the previous one. 
Like this the non-success validations would also be prevented.  Very nice idea.

**Comment by sophokles73** [comment]
@Christian-Schmid With #3302 this should now be possible.

**Comment by sophokles73** [comment]
Closed via #3302
