### ISSUE TITLE
LoRa adapter: Create only one gateway device command consumer per application instance

### ISSUE THREAD

**Issue by calohmn** [eclipse-hono/hono#2726]
Apply some minor Command & Control improvements:
A command subscription for a gateway device only needs to be done once for the whole LoRa adapter application - currently the corresponding `LoraProtocolAdapter#commandSubscriptions` map is kept per `LoraProtocolAdapter` verticle instance.

Along with that, the closing of command consumers in the `handleTenantTimeout` method (introduced in #2720) should then effectively only be done once per gateway device (not for up to as many times as the number of verticles as it is now).

**Comment by calohmn** [comment]
Some background info here:
Let's suppose a running LoRa adapter container contains 4 `LoraProtocolAdapter` verticle instances.
Each of that instance refers to a separate `InternalCommandConsumer` instance, keeping its own adapterInstanceId (with the verticle instance index as last part).

When a HTTP request from gateway device A to the adapter is handled by verticle instance 1, `LoraProtocolAdapter#registerCommandConsumerIfNeeded` is invoked and the command consumer is registered in the Command Router associated with the adapterInstanceId for verticle instance 1. 

When a subsequent HTTP request from the same gateway device A to the adapter is handled by verticle instance *2*, `LoraProtocolAdapter#registerCommandConsumerIfNeeded` is invoked and the command consumer is registered in the Command Router associated with the adapterInstanceId for verticle instance *2*, overwriting the previous "device-to-adapterInstanceId"  mapping entry for instance 1.  That means that from that point on, incoming commands for the device are only handled by verticle instance *2*. The command handler created in instance 1 stays unused.

That is why the second command handler creation in the above example should be skipped.

**Comment by calohmn** [comment]
Along with the modifications here, a change towards using the `DeviceChangeNotification` mechanism for removing obsolete command consumers can also be done here. See: https://github.com/eclipse-hono/hono/issues/2704#issuecomment-1246754628

**Comment by sophokles73** [comment]
@calohmn @kduba can this be closed?

**Comment by calohmn** [comment]
yes, fixed via #3421.
