### ISSUE TITLE
Message order guarantees for events using MQTT protocol adapter

### ISSUE THREAD

**Issue by Christian-Schmid** [eclipse-hono/hono#3064]
Hi Hono, 

I've the following setup:
- Device is connected via MQTT to Hono MQTT protocol adapter
- MQTT protocol adapter is configured with Kafka based messaging

My device is performing the following actions:
- Pushing `Message A` via the `event` topic
- Pushing `Message B` via the `event` topic

I could observe that when the two events are pushed quickly consecutively they aren't published in the same order to the Kafka broker by the MQTT protocol adapter. 

So my application is receiving them in the following order:
- `Message B` 
- `Message A`

Using the jaeger instrumentation I could see that the messages are in fact received in the correct order by the MQTT adapter:
- `Message A` 2022-02-03T10:38:58.391427Z
- `Message B` 2022-02-03T10:38:58.391500Z

The total processing time for the two requests showed a difference of ~ 20 ms. (In one instance I guess some device registry interaction occurred). The traces indicate `Message B` was pushed first to Kafka and then `Message A`

My question: 

What would be the correct expectation? 

Can I assume that my messages are processed in the correct order? 

Or is this something I have to implement on my own (e.g. by waiting for successful `PUBACK` of `Message A` before I should proceed to publish `Message B`

Thanks!

Best regards
Chris

**Comment by calohmn** [comment]
To give some background on what was happening here in the MQTT adapter:
![mqtt_publish_2x](https://user-images.githubusercontent.com/891931/152793126-8337d1e7-f1e2-4dbd-b304-d181bcef45f8.png)

For both requests, the device-registration data had to be fetched from the device-registry - no cached data was available. Here the 2nd device registry request was being answered before the 1st one.

The incoming message order would most probably have been preserved if cached device registration data was used.

**Comment by Christian-Schmid** [comment]
I gave the issue some more tought:

To ensure the order of events (always qos 1) probably the "wait for PUBACK behaviour" would make the most sense. 

Lets assume the forwarding order would always be correct in the protocol adapter, then we still would run in the following scenario:
- Device pushes messages A
- Device pushes messages B
- Device pushes messages C

- Protocol adapter sends PUBACK for message A
- Protocol adapter sends **__no__** PUBACK for message B
- Protocol adapter sends PUBACK for message C

-> Device would need to resend message B as it was not confirmed by protocol adapter.
-> The backend however would have already received messages A and C

So in cases with qos >= 1 and a mattering message order, probably it is needed to limit the amount of in-flight messages to 1.

The issue however is still interesting for qos 0 messages. For example a device publishing telemetry messages and expects them in correct order, but would tolerate message loss in between.

**Comment by sophokles73** [comment]
> The issue however is still interesting for qos 0 messages. For example a device publishing telemetry messages and expects them in correct order, but would tolerate message loss in between. 

FMPOV that does not mean that we need to change the protocol adapter behavior but simply that the device needs to use QoS 1 with nstart=1 in that case.
