### ISSUE TITLE
Fix/clarify handling of empty telemetry/event message payload

### ISSUE THREAD

**Issue by calohmn** [eclipse-hono/hono#3222]
From https://github.com/eclipse/hono/pull/3215#discussion_r857397317:
A device trying to send a telemetry/event message with an empty payload will get a code 400 error if the content type of the message wasn't set to `application/vnd.eclipse-hono-empty-notification`.
That behaviour/requirement is not documented.

It's not obvious why messages with an empty payload require that content type. Before the introduction of that content-type, empty payloads were even not supported at all (see https://github.com/eclipse/hono/pull/596/files#diff-8a5c90291d6bfbbcbd7ae69c43de9a5a5e77532137e677c23fd3e655545d67c5L489).

At least the documentation should be adapted here.

**Comment by sophokles73** [comment]
Here's what I consider a reasonable behavior:

1. If the payload of a message is empty, then
   1. if the device specifies a content type, that content type is used for the downstream message,
   1. otherwise, the `application/vnd.eclipse-hono-empty-notification` content type is used.
1. Otherwise, if the payload is not empty, then
   1. if the device specifies a content type, that content type is used for the downstream message,
   1. otherwise, the `application/octet-stream` content type is used.

@calohmn WDYT?

**Comment by calohmn** [comment]
>     1. If the payload of a message is empty, then
>        
>        1. if the device specifies a content type, that content type is used for the downstream message,
>        2. otherwise, the `application/vnd.eclipse-hono-empty-notification` content type is used.
> 
>     2. Otherwise, if the payload is not empty, then
>        
>        1. if the device specifies a content type, that content type is used for the downstream message,
>        2. otherwise, the `application/octet-stream` content type is used.

@sophokles73 I agree.

**Comment by sophokles73** [comment]
@calohmn 

On second thought, I now think that we should never automatically set the `application/vnd.eclipse-hono-empty-notification` content type in the adapters. If a device wants to send an empty message without a content type, so be it. If the device is not per se able to set a content type, then a default content type can be defined for the device as well. However, in most cases, a device should be able to explicitly set the content type of the request payload.
One case of particular interest is a device sending a response to a command. If the response has no payload but just a status (e.g. 200 OK), then FMPOV it would not make much sense to set a default content type of `application/vnd.eclipse-hono-empty-notification`. Instead, the content type and payload should simply be kept empty.

WDYT?

**Comment by calohmn** [comment]
> On second thought, I now think that we should never automatically set the `application/vnd.eclipse-hono-empty-notification` content type in the adapters. If a device wants to send an empty message without a content type, so be it. 

Actually, yes. Such a Hono-specific content type on messages coming from devices might also confuse downstream applications. The applications might only expect such a content type on messages coming from Hono itself, i.e. on the messages signalling  readiness to receive commands.

> If the device is not per se able to set a content type, then a default content type can be defined for the device as well. 

The default content type (using `application/octet-stream` if none is set for the tenant) should then only be set if the payload is not empty, I think. See also #2349 here.

> One case of particular interest is a device sending a response to a command. If the response has no payload but just a status (e.g. 200 OK), then FMPOV it would not make much sense to set a default content type of `application/vnd.eclipse-hono-empty-notification`. Instead, the content type and payload should simply be kept empty.

I agree, treating command response messages the same as telemetry/event messages in this respect.

**Comment by sophokles73** [comment]
The Telemetry and Event APIs currently define the content-type as a mandatory message property. IMHO we therefore cannot make the content-type optional with a minor version update because downstream applications might rely on its existence in messages received from Hono.

So for 2.1.0 I guess we have two options:

1 The adapters reject empty (telemetry and event) messages that do not contain a content-type that they receive from devices for which no default content-type is defined.
1. We define an additional default content-type like `application/vnd.eclipse-hono-unknown`

Personally, I would prefer option 1. WDYT?

**Comment by calohmn** [comment]
Currently, in the Hono code preparing the Kafka/AMQP messages to be sent, the content-type for a non-null payload is set to `application/octet-stream` if no content-type was provided.
I think I would keep it that way.
Using `application/vnd.eclipse-hono-unknown` might cause downstream applications to reject the message if the application hasn't been adapted to know this special content type. I think the generic `application/octet-stream` would be a better solution here.
And rejecting such messages outright does seem too restrictive to me.

**Comment by sophokles73** [comment]
> Currently, in the Hono code preparing the Kafka/AMQP messages to be sent, the content-type for a non-null payload is set to application/octet-stream if no content-type was provided.
I think I would keep it that way.

Yes, that makes sense and will not break compatibility.

> Using application/vnd.eclipse-hono-unknown might cause downstream applications to reject the message if the application hasn't been adapted to know this special content type. I think the generic application/octet-stream would be a better solution here.

You mean that the adapters should use `application/octet-stream` if the message from the device is empty and has no content-type?

**Comment by sophokles73** [comment]
The MQTT adapter interprets an empty telemetry message as a device's intent to send an empty notification. That makes some sense because the device cannot (easily) provide a content-type explicitly apart from using a property bag in the topic (which nobody does, I guess). Changing the default content type being used in the downstream message in this case to `application/octet-stream` might therefore prevent existing devices from sending empty notifications ...

**Comment by calohmn** [comment]
> You mean that the adapters should use `application/octet-stream` if the message from the device is empty and has no content-type?

Yes. That would mean letting the adapters keep the decision which default content type to use in the end to the called `AbstractKafkaBasedDownstreamSender#addDefaults` and `AmqpUtils#setPayload` methods.

> The MQTT adapter interprets an empty telemetry message as a device's intent to send an empty notification. 

Can you elaborate on where this is defined or becomes obvious? I haven't found such a place in the code.

**Comment by sophokles73** [comment]
> Can you elaborate on where this is defined or becomes obvious? I haven't found such a place in the code.

Now that you mention it: neither did I ;-) I had just assumed that this was the case but it looks like it isn't. So an MQTT device actually MUST explicitly set the content-type via the property bag in order to send an empty notification and the same seems to be true for the HTTP adapter.

So, the strategy would now be:

1. If the payload of a message is empty, then
    1. if the device specifies a content type, that content type is used for the downstream message,
     1. otherwise, the application/octet-stream content type is used.
1. Otherwise, if the payload is not empty, then
    1. if the device specifies a content type, that content type is used for the downstream message,
    1. otherwise, the application/octet-stream content type is used.

Right?

**Comment by sophokles73** [comment]
Wouldn't it make more sense to actually use `application/vnd.eclipse-hono-empty-notification` as the downstream message's content-type if the device uploads an empty message with no content-type? Using `application/octet-stream` feels wrong since there is no octet stream available, is there? Also, this way it would be easier for devices to send empty notifications ...

**Comment by sophokles73** [comment]
@calohmn WDYT?

**Comment by calohmn** [comment]
>     1. If the payload of a (telemetry or event) message is empty, then
>        
>        1. if the device specifies a content type, that content type is used for the downstream message,
>        2. otherwise, if a default content-type is defined for the device, then that value is used,
>        3. otherwise, the `application/vnd.eclipse-hono-empty-notification` content type is used.
> 
> [...]
> This way we could also provide an easier way for devices to send empty notifications ... Does that make sense?

I see benefits here with regard to sending `hono-ttd` messages without payload with the HTTP and CoAP adapters.

For the MQTT and AMQP adapter, I don't really see a need to make it easier to send `application/vnd.eclipse-hono-empty-notification` messages from the devices. It might even be a bit confusing for downstream application developers seeing messages from MQTT/AMQP devices without content type and payload being mapped to the empty-notification content type, when such empty-notification content type messages are otherwise associated with ttd-messages.

Therefore, I wonder whether we shouldn't apply the `application/vnd.eclipse-hono-empty-notification` content type only for HTTP/CoAP messages with `hono-ttd` parameter and empty payload and empty content type (of message or device-default).
In case no `hono-ttd` is set and payload and content type are empty, we could use `application/octet-stream` as well, meaning an empty stream then.

**Comment by sophokles73** [comment]
> It might even be a bit confusing for downstream application developers seeing messages from MQTT/AMQP devices without content type and payload being mapped to the empty-notification content type, when such empty-notification content type messages are otherwise associated with ttd-messages.

I see your point. AMQP and/or MQTT devices actually have no reason to send empty notifications in the first place.

I can also see the benefit of using the existence of a `hono-ttd` request parameter in conjunction with an empty and empty content type in the HTTP and CoAP adapters. For CoAP and HTTP devices this would allow them to omit the explicit content-type, thus further reducing request message size.

I am still not convinced of using `application/octet-stream` as a fallback content type for other empty messages, though. We currently do not support sending empty messages with another content-type than `application/vnd.eclipse-hono-empty-notification` at all. So I can also imagine to relax this a little and allow devices to send empty messages with *any non-null* content type instead. WDYT?

**Comment by calohmn** [comment]
> I am still not convinced of using `application/octet-stream` as a fallback content type for other empty messages, though. We currently do not support sending empty messages with another content-type than `application/vnd.eclipse-hono-empty-notification` at all. So I can also imagine to relax this a little and allow devices to send empty messages with _any non-null_ content type instead. WDYT?

Ok, so then the only change for this issue here and Hono 2.1.0 would be allowing messages with empty payload and any non-null content-type.
For Hono 3.0 we could do the change towards allowing an empty content-type along with an empty payload.

Concerning the case that an empty device message with no content-type is received and there is a default configured for the device: 
If the default is `application/json` for example, setting that content-type for an empty message would result in an inconsistent/invalid message, as an empty payload would not represent valid JSON. Therefore I think it would be better to apply the device-default content type only for non-empty messages.
