### ISSUE TITLE
MQTT Port collision

### ISSUE THREAD

**Issue by PJC-IONOS** [eclipse-hono/hono#3408]
Hi all.

I am having some troubles in installing the Eclipse-Hono with helms.

The error is the following:
Error: INSTALLATION FAILED: Service "eclipse-hono-adapter-mqtt" is invalid: spec.ports[0].nodePort: Invalid value: 31883: provided port is already allocated

In my K3S cluster, I have a solution working that uses the MQTT and therefore the 31883 port.

Is it possible to change the ports of the NodePorts in the installation process? I didn't see anyhing related to that matter in the values.yaml file (https://github.com/eclipse/packages/blob/master/charts/hono/values.yaml).

Thanks.

**Comment by sophokles73** [comment]
This is the GitHub repository where the Hono code is maintained. The Helm chart is being maintained in the [Eclipse IoT Packages project](https://github.com/eclipse/packages). Can you please create an issue there or, even better, use the [corresponding Gitter channel](https://gitter.im/eclipse/packages) to post your question?

**Comment by PJC-IONOS** [comment]
Yes, of course. I will do that. 

Thanks.
