### ISSUE TITLE
Support Mongo DB 5.0

### ISSUE THREAD

**Issue by sophokles73** [eclipse-hono/hono#3411]
Currently, all tests are being run using Mongo DB 4.4. However, Mongo DB 5.0 and 6.0 are already available and we should make sure that we at least support Mongo DB 5.0. If any steps are required to migrate an existing Mongo 4.4 based registry to Mongo 5.0, these steps should be ideally performed automatically or (at least) be documented in the admin guide.

**Comment by n-deliyski** [comment]
I'd like to work on that. Could you assign it to me?

**Comment by sophokles73** [comment]
@n-deliyski be my guest :-)

**Comment by sophokles73** [comment]
Great work :+1: I guess that is about what I would have tested as well. I guess it would be worthwhile to get an understanding of how a migration of an existing Mongo DB 4 to version 5 (and/or 6) would look like, i.e. if there is anything special that needs to be taken care of regarding indexes etc. Maybe the Mongo DB contains some information regarding this topic?

**Comment by n-deliyski** [comment]
I have read the following compatibility guides from MongoDB:
https://www.mongodb.com/docs/v5.0/release-notes/5.0-compatibility/
https://www.mongodb.com/docs/v6.0/release-notes/6.0-compatibility/
Also I have gone through the source code of Hono DB DAO layer at hono/services/device-registry-mongodb/src/main/java/org/eclipse/hono/deviceregistry/mongodb/model. 	

My input is:
- The compatibility guides have a lot information. Maybe it make a sense to do additional tests per each version. For example create new tenant, device, post messages.	
- There is nothing that could break the Hono regarding indexing.
- During upgrade 4.4 to 5.0 the deprecated geoHaystack index is removed. Such index is not used by Hono.
- During upgrade 5.0 to 6.0 there is change if dropIndex is called with "*" wildcard. Hono is not using that pattern.
- Hono uses the Vertx mongo db client - https://vertx.io/docs/vertx-mongo-client/java/
I could not find any notes about compability issues for that client.

**Comment by sophokles73** [comment]
Sounds good. So which version do you suggest Hono should use for running tests from now on?
IMHO it would also be good to add some statement regarding compatibility to the Mongo Registry's Admin Guide.

**Comment by n-deliyski** [comment]
The [EOF schedule](https://www.mongodb.com/support-policy/lifecycles) for 4.4 and 5.0 is in 2024 and for 6.0 is 2025.
I found one [benchmark](https://serpapi.com/blog/the-downfall-of-mongodb-performance-2) that shows controversial results. 5.0 does not stand out with something. 6.0 has better query times. 
The benefit of 5.0 and 6.0 is the new set of features. But my understanding is that Hono is not going to use them.

I would suggest to stay at the current version 4.4 for one more year.
We could add statements regarding compatibility to the Mongo Registry's Admin Guide.

**Comment by sophokles73** [comment]
> I would suggest to stay at the current version 4.4 for one more year.

Sounds reasonable.

> We could add statements regarding compatibility to the Mongo Registry's Admin Guide.

You mean, indicating that Hono will also work with Mongo 5.0 and 6.0?

**Comment by n-deliyski** [comment]
Yes exactly.

**Comment by sophokles73** [comment]
Then please, go ahead :-)

**Comment by n-deliyski** [comment]
I have spend some time to see the options for testing different mongo db versions during development.

a) There are JUnit tests (located at services/device-registry-mongodb) that bring up real mongo db using testcontainer framework.
The triggering for different mongo version is like this:
mvn test -Dmongodb-image.name=mongo:5.0
mvn test -Dmongodb-image.name=mongo:6.0
Those tests checks the functionality partially.
Also it seems there is a bug in testcontainer when mongo 6.0 is used. See https://github.com/testcontainers/testcontainers-java/issues/5768

b) There are the integration tests.
The triggering for different mongo version is like this:
mvn verify -Prun-tests -Dmongodb-image.name=mongo:5.0
mvn verify -Prun-tests -Dmongodb-image.name=mongo:6.0

I think option b) is better as it has better use case covering.
But I am not sure how to automate calling b). Maybe it is possible add those commands to the verification steps called on each branch push? 
An other thought is that integration tests take time and if those "compatibility" tests are added by default to the integration tests the whole execution time will increase 3 times. 
Any idea how to proceed on this issue?

**Comment by sophokles73** [comment]
With option b we would need to adapt the `.github/workflows/ci.yml` file to run the tests for different types of Mongo DB. FMPOV we would not need to run all combinations but e.g. only run the last variant with multiple Mongo DB versions.

**Comment by n-deliyski** [comment]
> FMPOV we would not need to run all combinations but e.g. only run the last variant with multiple Mongo DB versions.

I am not sure if understand that completely. Could you give a example?

**Comment by n-deliyski** [comment]
I have tried matrix `device-registry: [file,jdbc,mongodb]` but it is not enough, as iterates only on one mongodb type - the last one(6.0). Thus I have created `device-registry-name: [file,jdbc,mongodb-4.4,mongodb-5.0,mongodb-6.0]`, is ok?

**Comment by sophokles73** [comment]
closed via #3435
