### ISSUE TITLE
Remove documentation for very outdated Hono versions from website

### ISSUE THREAD

**Issue by sophokles73** [eclipse-hono/hono#3417]
We currently keep documentation for all versions but I do not believe that it is very useful to have the docs online for versions that we would never want anybody to use at all. I suggest to remove all docs before version 1.12. If needed, users can still build the docs from the source code ...

**Comment by avgustinmm** [comment]
I also think there is no need to keep these docs on site. Only supported versions should be sufficient.
If there is agreement on this I could remove versions before 1.12

**Comment by sophokles73** [comment]
@calohmn any thoughts?

**Comment by calohmn** [comment]
I'm ok with removing the docs before version 1.12.

**Comment by sophokles73** [comment]
@avgustinmm please go ahead :-)
