### ISSUE TITLE
Do we still need support for using an embedded cache with the Command Router?

### ISSUE THREAD

**Issue by sophokles73** [eclipse-hono/hono#3425]
For production use cases the Command Router supports storing routing information in an Infinispan data grid. However, it can also be configured to use an embedded (in-memory only) cache which can be used in development and/or test environments. Such a setup effectively limits the Command Router to a single instance only because the data in the cache is neither shared nor replicated.

It seems questionable if we still need the embedded cache option or if we can simply stick to the Infinispan based approach. In the end, setting up a small scale test environment would also be possible using a single node Infinispan cluster ...

It might, however, also be an option to replace the simplistic embedded cache option that we use today with a more elaborated configuration that would allow the embedded cache to be replicated across multiple Command Router instances.

**Comment by BobClaerhout** [comment]
Our dev and test environment also uses infinispan so we have no objection against removing the in-memory cache

**Comment by sophokles73** [comment]
@calohmn any thoughts/doubts?

**Comment by calohmn** [comment]
I agree that using the embedded cache option and thereby only allowing one Command Router instance doesn't fit well with Hono's overall focus on scalability. For deployments using only telemetry/event messages that cache option would be ok though.

My only doubt concerning the removal of the embedded cache option would be concerning the overall memory/CPU usage in Hono demo deployments via the IoT Packages charts.
I'm thinking about the cloud2edge chart here for example, already requiring quite many resources.

Therefore, I would prefer to first evaluate changing the embedded cache configuration to a distributed cache, spanning across all Command Router instances, as mentioned in the issue description above. A Kubernetes-based discovery protocol could be used here.

In general, an alternative to Infinispan is also discussed in #3294, but that would be a bigger change, as it seems.

**Comment by sophokles73** [comment]
@calohmn are you going to evaluate the *distributed cache* option? If not, i would propose to go ahead and remove the embedded cache from the Command Router ...

**Comment by calohmn** [comment]
@sophokles73 I'm going to look into the distributed cache option, yes.

**Comment by calohmn** [comment]
@sophokles73 I've gotten the distributed cache option to work. This doesn't require changes in Hono itself, it only means configuring the embedded cache manager to use a corresponding configuration file, referencing it in the `hono.commandRouter.cache.embedded.configurationFile` property. In this file, the Kubernetes-targeted `/default-configs/default-jgroups-kubernetes.xml` JGroups configuration file from the infinispan-core distribution can be referenced, along with the distributed cache configuration.

I would therefore suggest keeping the embedded cache option in Hono.
I'll look into creating a PR in the iot-packages project to have the distributed embedded cache as a configurable option there.
