### ISSUE TITLE
Add support for using JSON format when logging to console

### ISSUE THREAD

**Issue by vhdirk** [eclipse-hono/hono#3427]
We're migrating all our services to log in json format. It'd be nice if hono could follow suit.
Just like gelf, quarkus supports logging in json by setting the env var `QUARKUS_LOG_CONSOLE_JSON`, if the dependency `quarkus-logging-json` is added.

**Comment by sophokles73** [comment]
Sounds reasonable to me :-) However, IMHO we should always include the `quarkus-logging-json` extension in the Hono container images and let users configure the logging they want by means of the configuration properties (which are not fixed at build time, if I am not mistaken).

**Comment by vhdirk** [comment]
By default, just including that library just adds support but does nothing more. You need the environment variable or an entry the application settings to change the default logging format to json
