### ISSUE TITLE
Unexpected/undocumented MQTT behaviour when receiving commands via gateway

### ISSUE THREAD

**Issue by n-deliyski** [eclipse-hono/hono#3432]
The following cases are not covered in the [documentation](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#receiving-commands-authenticated-gateway). It is also not clear if this should work like that.

1. When authenticated gateway device subscribes for topic `command///req/#`
- it will receive commands directed to the gateway itself (e.g `command///start`) and
- it will receive commands for directed to devices behind that gateway (e.g `command//device1/start`).

This topic works the same as `command//+/req/#`.

2. When authenticated gateway device subscribes for topic `command//<gateway-id>/req/#`
- it will receive commands directed to the gateway itself (e.g `command//gateway1/start`) and 
- it will receive commands directed to devices behind that gateway (e.g `command//device1/start`).
Is it is normal to receive the commands directed to the devices behind this gateway?

Similar topic has been covered already at https://github.com/eclipse-hono/hono/issues/3412

**Comment by avgustinmm** [comment]
According Hono documentation commands (for instance one-way commands) will be send to 
`command/[${tenant-id}]/${device-id}/req//${command}` for a device behind gateway and to `command/[${tenant-id}]//req//${command}` for the gateway itself. Following that and expectation of MQTT filter resolution I would expect that:
1. For subscription `command///req/#` - only command for gateway would be received
2. For subscription `command//<gateway-id>/req/#` - no command would be received at all - hono declare that gateways command will be send with missing device id segment

I think that Hono shall specify explicitly topics (as it does) and the filters shall work as much in accordance with MQTT as possible

**Comment by n-deliyski** [comment]
@avgustinmm 
for 1) I agree
for 2) you mean this statement `the device-id segment in all cases except when the command was explicitly directed at the gateway itself`, right?

**Comment by avgustinmm** [comment]
yes exactly. I interpret it as - if command is sent to gateway it would be not with gateway id but empty segment. 
though, I think it is more natural if command to gateway are send with gateway id - the same as to device. In that case gateway is simply a device (with device id equal to gateway id) and should keep same behavior.

**Comment by e-grigorov** [comment]
I am confused here, it seems that the last two comments are not aligned:
- `for 2) you mean this statement the device-id segment in all cases except when the command was explicitly directed at the gateway itself, right?` - except is used i.e. the gateway-id is not used in the topic
- `In that case gateway is simply a device (with device id equal to gateway id)` - this means that gateway-id is used

Could you please clarify the expectations with some examples?

**Comment by avgustinmm** [comment]
current approach is that commands to gateway shall be send with empty device id segment - according documentation
the second one is just my opinion that this should not be like that but gateway id shall be used as id segment.

**Comment by sophokles73** [comment]
>  When authenticated gateway device subscribes for topic command///req/#
>
> 1. it will receive commands directed to the gateway itself (e.g command///start) and
> 2. it will receive commands for directed to devices behind that gateway (e.g command//device1/start).

FMPOV the gateway device should not receive commands directed to devices that connect via the gateway in this case. The user guide clearly states that for the latter purpose, the `c//+/q/#` topic needs to be used.

@calohmn WDYT?

**Comment by calohmn** [comment]
> FMPOV the gateway device should not receive commands directed to devices that connect via the gateway in this case. The user guide clearly states that for the latter purpose, the c//+/q/# topic needs to be used.

Yes, it would be consistent for both the `command///req/#` and `command//<gateway-id>/req/#` subscription filters to _not_ include messages directed at devices behind the gateway. 
And if `command//<gateway-id>/req/#` was used, the topic that the command is published to should also contain the gateway id - just as it is documented in the "Receiving Commands (authenticated Device)" [chapter](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#receiving-commands-authenticated-device). For such a subscription filter, the gateway is treated as a "normal" device then.

There is one thing to note here however in terms of the current subscription registration implementation in the command router:
The ["Register command consumer for device"](https://www.eclipse.org/hono/docs/api/command-router/#register-command-consumer-for-device) Command Router API operation just contains a single device id. This means there currently is no distinction between registering a command consumer for commands directed at the gateway itself and a command consumer for commands directed at specific devices behind a gateway.

With that implementation we can't support a scenario where a gateway uses both `command//<gateway-id>/req/#` and `command//+/req/#` filters at the same time. (The user's motivation for that could be a wish to separate gateway and device-behind-gateway commands, doing the subscriptions in separate MQTT connections.)
Using both kinds of subscriptions in separate MQTT connections, and these connections being with different MQTT adapter instances, the last such subscription would always "win" in terms of the Command Router subscription registration. This means the MQTT adapter that the previous subscription request was directed at, wouldn't receive any commands at all.

Therefore I think we should document for now, that both `command//[<gateway-id>]/req/#` and `command//+/req/#` filters can't be used at the same time.
We could consider changing the Command Router implementation here, but I wonder if this scenario is important enough to justify such a (non-trivial) change.

With the current Command Router implementation, usage of the `command//[<gateway-id>]/req/#` filter then means that commands directed at devices behind the gateway will be rejected at the MQTT adapter (i.e after having been routed there by the Command Router).

**Comment by n-deliyski** [comment]
Hi, could you assign me on that issue?

**Comment by sophokles73** [comment]
@n-deliyski sorry for the late reply. I have assigned the issue to you ...

**Comment by n-deliyski** [comment]
The fix is implemented.
