### ISSUE TITLE
how to get data from hono to jhipster-Ionic application using http get requests

### ISSUE THREAD

**Issue by akhilveramalli** [eclipse-hono/hono#3437]
I am using hono to get IoT Data to my Jhipster-Ionic Application. How to
a) send http get request to hono api, to fetch data and show it on my echarts dashboard. b) How do i send commands back to Hono using my application to control my IoT devices? c) how do i send hono data into postgres database (my application database) for showing historic data). THANKS

**Comment by sophokles73** [comment]
a) You can't. Hono writes the telemetry and event messages it receives from devices to Kafka topics. Applications that want to process the messages therefore need to create a corresponding Kafka Consumer an can then do with the data whatever they see fit. See https://www.eclipse.org/hono/docs/api/telemetry-kafka/#northbound-operations for details regarding the topic structure and message format.
b) You can use Hono's (Kafka topic based) north bound Command & Control API for this. See https://www.eclipse.org/hono/docs/api/command-and-control-kafka/
c) see a)

**Comment by sophokles73** [comment]
@akhilveramalli can this be closed?
