### ISSUE TITLE
Support JWT based device authentication (Google IoT Core like authentication)

### ISSUE THREAD

**Issue by julian-sotec** [eclipse-hono/hono#3441]
This is the first of multiple issues we will submit in order to qualify Hono as a replacement for Google IoT Core customers (IoT Core is being retired in August 2023). One of the gaps is the special authentication that IoT Core provides. It is based on private / public key signed JWTs that are sent in the password field during MQTT CONNECT (see https://cloud.google.com/iot/docs/concepts/device-security for details). 
To our knowledge Hono right now does not offer such authentication method out of the box. As part of this architecture we would like to add a new device authentication method to Hono’s auth chain using JWT in addition to the existing basic Username/password and X.509 based authentication. This authentication would support manual device provisioning only for now via the device management API. Implementation would be for the MQTT adapter.

Provisioning: 
- Provide public key of the device via device management api
- Key stored as credentials object in Hono

Authentication: 
- device needs to provide JWT signed with private key in the password field
- Hono auth chain validates JWT using public key (via SigningKeyResolver)

We are happy to provide more information on implementation details if desired.

**Comment by sophokles73** [comment]
In general, I do not see an issue with adding another auth mechanism to the MQTT adapter. Have you already thought about where and how this functionality would need to be implemented?

**Comment by julian-sotec** [comment]
> In general, I do not see an issue with adding another auth mechanism to the MQTT adapter. Have you already thought about where and how this functionality would need to be implemented?

Since Hono already includes abstract classes and interfaces for, handler, provider and credentials we would write add our own classes that implement / extend the already existing interfaces. List of concrete classes 
- JwtAuthProvider extends CredentialsApiAuthProvider<JwtCredentials>
- JwtCredentials extends AbstractDeviceCredentials
- JwtAuthHandler extends ExecutionContextAuthHandler<MqttConnectContext>
- JjwtAuthTokenValidator extends JwtSupport implements AuthTokenValidator

In order for the new authentication method to be usable, we will inject our AuthHandler implementation to the ChainAuthHandler which is used by hono to find the right authentication method for every device.

**Comment by sophokles73** [comment]
That sounds about right :-) However, I do not believe that you would need to provide an implementation of *AuthTokenValidator*. The validation of the JWT provided by the device should probably simply be done in the *JwtAuthProvider* using the JJWT API directly, based on the credentials on record for the device.

**Comment by sophokles73** [comment]
@julian-sotec can this be closed?
