### ISSUE TITLE
Support Google Pub/Sub as telemetry data message infrastructure

### ISSUE THREAD

**Issue by julian-sotec** [eclipse-hono/hono#3442]
This is the second issue to qualify Hono as a replacement for Google IoT Core customers. (see #3441)
As part of this architecture we would like to add native Pub/Sub messaging infrastructure support to Hono. We want to adapt the same topic structure that Hono uses for Kafka messaging. The PubSub message should contain the same header information as as on Google IOT Core.
Internal communication between services will continue to use AMQP. Hono does support sending commands to the devices via Kafka messages. This will not be supported in Pub/Sub for now, instead we intend to implement this via REST API.
The Pub/Sub bridge should work foremost with MQTT, maybe later it could be extended with another protocol adapter.

Pub/Sub Messaging:

- Same topic structure is created (telemetry/event) as for kafka
- PubSubMessage contains same attributes as if Google IoT Core publishes the message (Same concept as KafkaHeaders) - see https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#publishing_telemetry_events
- Downstream messages are ingested to pub/sub instead of kafka

**Comment by sophokles73** [comment]
> Internal communication between services will continue to use AMQP. Hono does support sending commands to the devices via Kafka messages. This will not be supported in Pub/Sub for now, instead we intend to implement this via REST API.

Would you mind providing a little more detail regarding the REST API that you envision? Would that become a standard Hono API? If so, where do you see this API to be added?

**Comment by matthiasfeurer** [comment]
> > Internal communication between services will continue to use AMQP. Hono does support sending commands to the devices via Kafka messages. This will not be supported in Pub/Sub for now, instead we intend to implement this via REST API.
> 
> Would you mind providing a little more detail regarding the REST API that you envision? Would that become a standard Hono API? If so, where do you see this API to be added?

We would submit a separate issue for the REST API, but to give a short answer here: this would most probably be a new API talking to the Command Router so that all upstream logic via MQTT Adapter can stay the same as is. Terminology wise we would try to comply with Hono standards, so that it can be included into the core project. We will provide more details in the separate issue.

**Comment by sophokles73** [comment]
@julian-sotec can this be closed? It looks like the corresponding implementation has been contributed already.

**Comment by julian-sotec** [comment]
> @julian-sotec can this be closed? It looks like the corresponding implementation has been contributed already.

Done, Thanks for the hint!
