### ISSUE TITLE
External Kafka integration with hono

### ISSUE THREAD

**Issue by ishwar25667** [eclipse-hono/hono#3457]
Hi @sophokles73 

I was trying to configure external kafka with hono adapters but getting below issue. Could you please guide me what I am missing here. I am following below documentation-
https://github.com/eclipse/packages/tree/master/charts/hono#integrating-with-an-existing-kafka-cluster

messagingNetworkTypes:
- "kafka"

amqpMessagingNetworkExample:
  enabled: false

kafkaMessagingClusterExample:
  enabled: false

adapters:
  kafkaMessagingSpec:
    hono:
      kafka:
        commonClientConfig:
          bootstrap.servers: "x.x.x.x:29093"
          
Getting issue-

Error: INSTALLATION FAILED: execution error at (hono/templates/hono-service-device-registry-embedded/hono-service-device-registry-secret.yaml:77:10): At least 'bootstrap.servers' MUST be provided if example Kafka cluster is disabled

while running below command-
helm install eclipse-hono eclipse-iot/hono -n hono --wait -f customKafkaCluster.yaml

**Comment by sophokles73** [comment]
Can you try to put *bootstrap.servers* into '"':
```json
  kafka:
   "bootstrap.servers": "..."
```

**Comment by ishwar25667** [comment]
Thanks for your reply.
Instead of using external kafka right now I am using internal one. But as I understand we have to pass some others properties as well along with "bootstrap.servers".

**Comment by sophokles73** [comment]
That depends on the configuration of your standalone Kafka, e.g. does it require clients to authenticate, verify a server certificate etc. You can refer to the Kafka documentation for the particular properties you need to set ...
