### ISSUE TITLE
How can I set the partition and replication of the topic created by hono?

### ISSUE THREAD

**Issue by jpforevers** [eclipse-hono/hono#3461]
I installed Hono through [helm](https://github.com/eclipse/packages/tree/master/charts/hono). How can I set the partition and replication of the kafka topic(e.g. hono.telemetry.[tenantId], hono.event.[tenantId]) created by hono?

**Comment by sophokles73** [comment]
@calohmn Can you jump in on this?

**Comment by calohmn** [comment]
@jpforevers The Kafka topics for telemetry, event and command & control messages are not explicitly created by Hono.
That means that the topics either have to be created in advance (via some admin client connecting to Kafka) before Hono receives messages for the corresponding tenant, or the topics will need to get auto-created when the Hono Kafka clients first use them.
For the latter case, the `auto.create.topics.enable` broker configuration property needs to be set to `true` and partition number/replication factor get set according to the `num.partitions`/`default.replication.factor` broker config properties then.
The different Kafka topics used by Hono are listed here: https://www.eclipse.org/hono/docs/admin-guide/kafka-config/#used-topics

**Comment by jpforevers** [comment]
Great! I fully understand how to do it. Thank you very much. @calohmn You are noble man. May God bless you.
