### ISSUE TITLE
Device does not wait for a response even specifying hono-ttd=60 

### ISSUE THREAD

**Issue by Lando-Ant** [eclipse-hono/hono#3466]
I am using Eclipse Hono and I am experiencing an issue with hono-ttd, that is, when I launch the HTTP POST command from the device to send telemetry data by specifying e.g. hono-ttd=60, the device does not wait to receive a command instead it continues its execution. Moreover, I have no idea where to found the hono-cmd-req-id that should be returned by the device receiving the command.

This is the command I used to send telemetry data from the device:
` curl -i -u demo-device@org.eclipse.packages.c2e:demo-secret -H 'application/json' --data-binary '{ "topic": "org.eclipse.packages.c2e/demo-device/things/twin/commands/modify", "headers": {}, "path": "/features/temperature/properties/value", "value": 45 }' http://${HTTP_ADAPTER_IP}:${HTTP_ADAPTER_PORT_HTTP}/telemetry?hono-ttd=60`
 After sending the above telemetry data, I expect the device to wait for a command. Instead, the device does not wait and immediately returns: 
`HTTP/1.1 200 OK hono-command: modify-response content-type: application/vnd.eclipse.ditto+json content-length: 361 `

Thanks in advance for helping out!

**Comment by sophokles73** [comment]
Your device already has received a (one-way) command from Ditto as indicated by the HTTP reponse's content-type *application/vnd.eclipse.ditto+json*. Ditto has sent this one-way command in response to your modify message. The HTTP response will only contain a `hono-cmd-req-id` header if an application sends a *request-response* command for which the application expects the device to send a response by means of POSTing to the HTTP adapter's `/command/res/` resource (see https://www.eclipse.org/hono/docs/user-guide/http-adapter/#sending-a-response-to-a-command-authenticated-device).

If you want to see the device waiting for a command instead, you should send an *empty-notifcation* by means of POSTing an HTTP request with no payload to the HTTP adapter:
```sh
curl -XPOST -u demo-device@org.eclipse.packages.c2e:demo-secret -H 'content-type: application/vnd.eclipse-hono-empty-notification' http://${HTTP_ADAPTER_IP}:${HTTP_ADAPTER_PORT_HTTP}/telemetry?hono-ttd=60
```
In this case, Ditto will not find any message to process and will therefore not send the one-way command acknowledging the modify message ...

**Comment by Lando-Ant** [comment]
Thank you @sophokles73, so how should I retrieve the `hono-cmd-req-id`?

**Comment by Lando-Ant** [comment]
Simply I run 
`minikube start`
And after waiting for all the pods to be up and running, I run the command I posted in the first comment from a terminal. I expected the `hono-cmd-req-id` to appear in the output but it does not.

**Comment by sophokles73** [comment]
@Lando-Ant is this still an issue?

**Comment by sophokles73** [comment]
Please re-open if you still experience this problem.
