### ISSUE TITLE
Use Pub/Sub as only messaging infrastructure

### ISSUE THREAD

**Issue by michelleFranke** [eclipse-hono/hono#3471]
This issue is part of the adaption process in order to qualify Hono as a replacement for Google IoT Core customers. (see https://github.com/eclipse-hono/hono/issues/3441, https://github.com/eclipse-hono/hono/issues/3442) 

We want to leverage Hono to natively use Google's scalable messaging infrastructure without the need of deploying Kafka or Amqp when deploying Hono to a Google Cloud Project.

In order to use the native Google Messaging Infrastructure Cloud Pub/Sub without the need to configure Kafka or Amqp, the Command Router has to be adapted to support Cloud Pub/Sub for routing the commands. The Command Router should utilize Cloud Pub/Sub for receiving the commands from the applications and forward the command to the Protocol Adapter instance that the device is connected to. Therefore there should be new implementation classes for the existing Command Router interfaces with a Pub/Sub based approach. Also the internal notification support between Hono components has to be adapted to use Cloud Pub/Sub for sending and receiving notification messages.

**More detailed this means we will:** 

- add a subscriber functionality with a factory like it is done for the Pub/Sub publisher

- add a new module “_notification-pubsub_” which includes a Pub/Sub based implementation  of clients for sending and receiving Hono’s notifications

- add a new module “_command-pubsub_” which includes a Pub/Sub based implementation of the client for Hono’s Command & Control API

- add a new implementation package “_pubsub_” which includes the Pub/Sub based implementation for the command-router API

**Pub/Sub Messaging:**

The same topic structure is created (command, command_response, command_internal, notification) as for Kafka with the Pub/Sub topic format:

- projects/PROJECT_ID/topics/TENANT_ID.command
- projects/PROJECT_ID/topics/TENANT_ID.command_response
- projects/PROJECT_ID/topics/ADAPTER_INSTANCE_ID.command_internal
- projects/PROJECT_ID/topics/registry-device.notification
- projects/PROJECT_ID/topics/registry-tenant.notification

Also Pub/Sub needs the following subscriptions in order to subscribe to a topic:

- projects/PROJECT_ID/subscriptions/TENANT_ID.command
- projects/PROJECT_ID/subscriptions/ADAPTER_INSTANCE_ID.command_internal
- projects/PROJECT_ID/subscriptions/registry-device.notification
- projects/PROJECT_ID/subscriptions/registry-tenant.notification

The Pub/Sub command message must contain the following attributes:

**_deviceId: string
tenantId: string
subject: string_**

If a response is required, the Pub/Sub command message must also contain the following attributes:

**_response-required: boolean
correlation-id: string_**

**Comment by michelleFranke** [comment]
@sophokles73 Can we open this issue again? Since the command router functionality is missing. I will add another 2 PRs and then we can mark this as complete.

**Comment by sophokles73** [comment]
sure, sorry for closing prematurely ...
