### ISSUE TITLE
hono with docker-compose

### ISSUE THREAD

**Issue by Gauravmeenu** [eclipse-hono/hono#3476]
How to run hono instance and connect with ditto with the help of docker-compose?

**Comment by sophokles73** [comment]
sorry, we only support installation via the [Helm chart](https://github.com/eclipse/packages/tree/master/charts/hono) maintained by the Eclipse IoT Packages project.

**Comment by Gauravmeenu** [comment]
Okay, so can you send me the link to the installation via helm chart?

**Comment by sophokles73** [comment]
I already did in my previous comment ...

**Comment by Gauravmeenu** [comment]
Okay, thank you.
