### ISSUE TITLE
Publishing telemetry for multiple devices?

### ISSUE THREAD

**Issue by mmcc-xx** [eclipse-hono/hono#3482]
Let's say I have a scenario where I have one gateway sending telemetry messages for multiple (10s or maybe 100s) of devices. To avoid authenticating for every update for every device, and to avoid other repeated back and forth communications, let's say I want to consolidate telemetry publications so that a single publication from the gateway contains updates for multiple devices.

It looks like that is not supported in the current adapters. Is that accurate?

If I wanted to enable this, would you suggest building a custom adapter?

**Comment by sophokles73** [comment]
I am not sure if I understand your question. It is a device that publishes telemetry messages via one of Hono's protocol adapters to *downstream* applications. Other devices do never get these messages. Maybe you are referring to *commands* that applications can send to individual devices?

**Comment by mmcc-xx** [comment]
In my scenario I have 10s to 100s of devices which can not communicate to a Hono adapter themselves, so they rely on a gateway to communicate for them - sending in telemetry and events and receiving commands. It is similar to the bluetooth device in this picture:

https://www.eclipse.org/hono/docs/concepts/connecting-devices/

but there are a bunch of bluetooth devices. The gateway, instead of servicing one device, is servicing many. (In my scenario, the devices aren't communicating to the gateway via bluetooth, but are likewise unable to communicate to the Hono adapter)

I'm trying to figure out how to consolidate the telemetry data from the many devices into fewer messages to the Hono adapter.

**Comment by sophokles73** [comment]
Ok, I see.

> To avoid authenticating for every update for every device

You could connect your gateway device to the MQTT or AMQP adapter and maintain the connection. This way, authentication would happen only during connection establishment.

> to avoid other repeated back and forth communications, let's say I want to consolidate telemetry publications so that a single publication from the gateway contains updates for multiple devices

Hono does not care about the payload of messages. Your gateway device could therefore locally buffer a certain number of messages originating from the edge devices and then periodically send a single batched telemetry message that contains the buffered messages.

You would then only need to make sure that your back end application can properly determine which message in the payload is coming from which edge device. This should only require defining some envelope for each message from the edge devices contained in the payload.

**Comment by mmcc-xx** [comment]
> Hono does not care about the payload of messages. 

That makes sense - thanks. I'm thinking of a situation where Hano is being used with Ditto. If I'm sending a payload with telemetry from mutliple devices, I would need something between Hano and Ditto that would parse that payload and send the right data to the right Ditto "things". Correct?

**Comment by n-deliyski** [comment]
At Ditto side that could be done via the payload mapping feature - https://www.eclipse.org/ditto/connectivity-mapping.html.
You could write a Javascript code at the Ditto connection that parses the big Hono telemetry message into multiple Ditto commands.

**Comment by sophokles73** [comment]
@mmcc-xx can this be closed?
