### ISSUE TITLE
Extend support of JWT based device authentication to HTTP adapter

### ISSUE THREAD

**Issue by mattkaem** [eclipse-hono/hono#3491]
Currently the Json Web Token (JWT) based device authentication mechanism is only supported by the MQTT adapter (see #3451). We want to enable this authentication mechanism also for the HTTP adapter. 

Implementation-wise we propose the following:

- There will only be small changes to the HTTP adapter needed since most of the implementation for the MQTT adapter was done in the adapter-base and other general modules and can therefore be reused.
- The JWT will be expected as a bearer token within the authorization header of a request.
- Equivalent to the MQTT implementation, the tenantId and authId will be extracted either from claims within the JWT or from the URI (e.g. /telemetry/tenantId/authId) of a request.

**Comment by sophokles73** [comment]
This seems (very much) related to #901.
Would you agree @mattkaem ?

**Comment by mattkaem** [comment]
> This seems (very much) related to #901. Would you agree @mattkaem ?

Definitively, however I would suggest we stick to the claims we already introduced for the MQTT adapter implementation (tid for tenant and sub for device).
