### ISSUE TITLE
Enable registering properties on devices that get set as record headers in the messaging infrastructure

### ISSUE THREAD

**Issue by StFS** [eclipse-hono/hono#3495]
It would be good to be able to register key/value pairs on specific devices in the device registry that would be injected in to records that these devices produce to the messaging infrastructure.

In our specific case, we have devices connect to the CoAP adapter and we use Kafka as the messaging infrastructure.

For a device with ID `4711`, when registered, it would be good to be able to store for example the device type or some information about the message schema used by the device to simplify routing in applications north of Hono. Any message coming from device `4711` would then be produced to the Kafka topic with the current available headers such as `device_id` but in addition, headers such as `device_type` and/or `message_schema` would be available as well.

There have been some discussions on this on the Gitter chat:
https://matrix.to/#/!xGWLKlpXndulTOvlHf:gitter.im/$mW3epr180aYC2iG0ewTS3As7lVJzOWG3vT1zkfr1RVE?via=gitter.im&via=matrix.org

There are also related issues such as #1618 and #1629 but these relate more to devices being able to store this information themselves and forward them with requests while this suggestions is to use the device registry to store this information instead and inject it into the records written to the messaging infrastructure.

**Comment by StFS** [comment]
It seems that this is in fact possible by using the `defaults` block when registering a [device](https://github.com/eclipse-hono/hono/blob/9d142c3b4e4a33fdbd9a020e261cb39ecfa6fcae/site/documentation/content/api/management/device-registry-v1.yaml#L1164) and/or a [tenant](https://github.com/eclipse-hono/hono/blob/9d142c3b4e4a33fdbd9a020e261cb39ecfa6fcae/site/documentation/content/api/management/device-registry-v1.yaml#L752) (they both refer to the same [DefaultProperties](https://github.com/eclipse-hono/hono/blob/9d142c3b4e4a33fdbd9a020e261cb39ecfa6fcae/site/documentation/content/api/management/device-registry-v1.yaml#L709) definition).

After a bit of wading through code and experimenting. It turns out that any property added to the `defaults` block (in either a tenant or a device) does in fact get propagated all the way down to the messaging infrastructure. This is at least the case in my scenario, using Kafka, as well as for both the CoAP and HTTP adapters.

Unless there is some hidden rule about not writing arbitrary properties in the `defaults` block, this solves my problem completely. We can simply register devices with additional information in the `defaults` block (such as `device-type` and `firmware-version`). To be on the safe side we'll namespace our properties to avoid clashing with anything that Hono might decide to add to the defaults block later.

**Comment by sophokles73** [comment]
Glad you found out about the *default* properties. There are indeed no specific rules and using an application specific prefix/namespace makes total sense.
