### ISSUE TITLE
CoAP - custom option range

### ISSUE THREAD

**Issue by boaks** [eclipse-hono/hono#3499]
Californium 3.8.0 introduced a improved API for CoAP custom option and also received a first issue, where  a CoAP custom option (see [Californium - Issue 2134](https://github.com/eclipse-californium/californium/issues/2134) may be used. That user uses Californium via Hono.

Such experimental custom options are based on the [IANA - CoAP Option Numbers](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#option-numbers) range reserved for experimental use 65000-65535.

If I remember well, hono is also already using a custom option.

To prevent future code-point conflicts, I would propose, that we agree on sub-range to be used by Californium, Hono, Users and Leshan (if Leshan wants that at all).

Feedback is welcome.

**Comment by sophokles73** [comment]
I think that this is a good idea. In Hono, we originally defined an option to convey a trace context. I always wanted to initiate the process for making this an *official* option but never did ...
Just out of curiosity, are there any specific *non-standard* options that we already use in Cf, or is this simply for *reserving a spot*?

**Comment by boaks** [comment]
> I think that this is a good idea. 

Great.

>  option to convey a trace context.

I remembered that, but I didn't found the code point, the source has changed too much since my last time ;-).
Could you please point me to it? 

>  making this an official option but never did ...

I guess, we need to talk with the IANA.

> Just out of curiosity, are there any specific non-standard options that we already use in Cf

Only for the examples (and that example is still in PR and not merged), for the core that seems for me not to make that much sense.

I currently use:
[0xff00 regular message interval](https://github.com/boaks/californium/blob/add_s3_proxy/demo-apps/cf-s3-proxy-server/src/main/java/org/eclipse/californium/cloud/s3/option/IntervalOption.java)
[0xff20 System time in milliseconds](https://github.com/boaks/californium/blob/add_s3_proxy/demo-apps/cf-cloud-demo-server/src/main/java/org/eclipse/californium/cloud/option/TimeOption.java)

0xff40, 0xff60 special options to piggyback a GET to a POST ;-).

All not even merged. I plan to change them to use a smaller range.

**Comment by boaks** [comment]
I'm not sure, if hono uses 65022 / 0xFDFE. If so, and if it's wanted to keep that, my proposal is:

(530 / 3 => 175)

    65000 - 65174 (hono experiments)
    65175 - 65349 (californium experiments)
    65350 - 65535 (users experiments)

**Comment by sophokles73** [comment]
I have tried to find the reference to the option we had used for the tracing context in the current Hono source code but didn't find it anymore. I guess we have removed it some time ago ;-)
So, in any case, I am fine with the segmentation you propose for the option numbers.

**Comment by sophokles73** [comment]
I have documented the agreed upon range in the [Developer Guide](https://www.eclipse.org/hono/docs/dev-guide/coap_adapter/)
