### ISSUE TITLE
One-way cloud-to-device messages are lost while MQTT device is offline

### ISSUE THREAD

**Issue by dimabarbul** [eclipse-hono/hono#3501]
I want to use Hono + Ditto (I install it using Cloud2Edge with Kafka based messaging infrastructure) to manage devices that support MQTT protocol and authenticate using client certificate and username/password pair.
The MQTT protocol adapter provided with Hono has [some limitations](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/), one of which is critical for me - messages sent while device is offline are lost.

What I'm looking for is a way to achieve guaranteed delivery of one-way cloud-to-device messages when device comes back online.

Options I see:

1. Implement [a protocol gateway](https://www.eclipse.org/hono/docs/concepts/connecting-devices/#connecting-via-a-protocol-gateway) that will support keeping messages while device is offline. As I understand, the protocol gateway will be responsible for authentication and mapping to target topics.
Drawbacks:
    - need to implement all functionality I need by myself
    - [template in hono-extras](https://github.com/eclipse-hono/hono-extras/tree/master/protocol-gateway/mqtt-protocol-gateway-template) might be a good starting point, but it does not provide even basic functionality, e.g., authentication using Hono APIs + I'm not Java developer, so it would be quite a challenge to me

2. Implement own adapter based on the one provided with Hono.
Drawbacks:
    - need to implement all functionality I need by myself
    - I'm not Java developer

3. Make Ditto publish one-way messages to "buffer" topic (e.g., hono.command-oneway-buffer.{tenant}.{device}) if device is not connected (check can be done using Ditto device twin), and to topic currently used by MQTT adapter (hono.command.{tenant}) if device is connected. Add custom application that will listen to connectivity events and requeue all messages for connected device from buffer topic to current topic.
Drawbacks:
    - order of messages might be wrong, for example:
        - application sends one-way message to buffer topic as device is disconnected
        - application sends two-way message and wait for the device to connect
        - device comes online, I believe, device will get two-way message first and then one-way message

All of the options have common drawback - I need to create and support another application.

I guess, possibility to keep messages while device is offline is relatively common thing to have, so I think, I might be missing something obvious, like configuration or easy setup to establish.

Could you, please, give some suggestion about the approach I should take to achieve not losing one-way messages while MQTT device is offline?

**Comment by sophokles73** [comment]
You will need to implement this in your application and listen to the connection events issued by Hono. Your application can implement any buffering that it seems necessary.
In any case, you should be aware that delivering a message to a device does not necessarily mean that the device has actually processed it. So, if you want/need to be sure that the device has actually processed the message, you should better use a request-response command instead.

**Comment by dimabarbul** [comment]
Thank you for the response.
As an alternative approach we started investigating using Mosquitto with Ditto, it might be more suitable for the task.
