### ISSUE TITLE
Connection to external KAFKA

### ISSUE THREAD

**Issue by paulocabrita-ionos** [eclipse-hono/hono#3510]
Hello everyone.

I'm trying to install HONO through `helm` and connect to an external kafka. Everything would run inside a K8S.

The KAFKA has a SSL configuration like the following:
- security.protocol=SSL
- ssl.truststore.type=PKCS12
- ssl.truststore.location=path_to_truststore
- ssl.truststore.password=password123

So, with that in mind, I try the following parameters for HONO:
- hono.kafkaMessagingClusterExample.enabled=false
- hono.adapters.kafkaMessagingSpec.commonClientConfig."bootstrap\.servers"=simple-kafka:9093
- hono.adapters.kafkaMessagingSpec.commonClientConfig."security\.protocol"=SSL
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.type"=PKCS12
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.location"=/tls/truststore.p12
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.password"=password123

Problems:
- HONO registry pod is saying me that it does not recognize the `ssl.*` parameters that I put. But, the parameters are compliant with the Apache Kafka Client configuration.

How can I connect to the external KAFKA?

I think it's related to this https://github.com/eclipse-hono/hono/issues/3457.

Help please.

Thanks

**Comment by sophokles73** [comment]
As this seems to be related to the Helm chart which is maintained in the [Eclipse Iot Packages project](https://github.com/eclipse/packages), would you mind posting your issue there?

**Comment by paulocabrita-ionos** [comment]
Ok. I will do it.

Thanks.
