### ISSUE TITLE
Running eclipse hono official example, error

### ISSUE THREAD

**Issue by yangdaren444** [eclipse-hono/hono#3512]
![image](https://github.com/eclipse-hono/hono/assets/139455943/c47d47bb-c0ee-4a3b-8b88-fe98a4756742)

**Comment by yangdaren444** [comment]
$ kubectl get service pods
Error from server (NotFound): services "pods" not found

yj@DESKTOP-O87AV3J MINGW64 /tmp
$ kubectl get service -n hono
NAME                                            TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
eclipse-hono-adapter-amqp                       LoadBalancer   10.109.128.51    127.0.0.1     5671:31523/TCP               11d
eclipse-hono-adapter-http                       LoadBalancer   10.103.215.177   127.0.0.1     8443:31731/TCP               11d
eclipse-hono-adapter-mqtt                       LoadBalancer   10.106.249.86    127.0.0.1     8883:32054/TCP               11d
eclipse-hono-kafka                              ClusterIP      10.97.160.127    <none>        9092/TCP,9094/TCP            11d
eclipse-hono-kafka-0-external                   LoadBalancer   10.110.240.155   127.0.0.1     9094:32094/TCP               11d
eclipse-hono-kafka-headless                     ClusterIP      None             <none>        9092/TCP,9093/TCP            11d
eclipse-hono-service-auth                       ClusterIP      10.97.247.33     <none>        5671/TCP,8088/TCP            11d
eclipse-hono-service-command-router             ClusterIP      10.100.101.104   <none>        5671/TCP                     11d
eclipse-hono-service-device-registry            ClusterIP      10.99.138.8      <none>        5671/TCP,8080/TCP,8443/TCP   11d
eclipse-hono-service-device-registry-ext        LoadBalancer   10.97.138.99     127.0.0.1     28443:31641/TCP              11d
eclipse-hono-service-device-registry-headless   ClusterIP      None             <none>        <none>                       11d
eclipse-hono-zookeeper                          ClusterIP      10.103.239.35    <none>        2181/TCP,2888/TCP,3888/TCP   11d
eclipse-hono-zookeeper-headless                 ClusterIP      None             <none>        2181/TCP,2888/TCP,3888/TCP   11d

yj@DESKTOP-O87AV3J MINGW64 /tmp
$ echo "export REGISTRY_IP=$(kubectl get service eclipse-hono-service-device-registry-ext --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" > hono.env
echo "export HTTP_ADAPTER_IP=$(kubectl get service eclipse-hono-adapter-http --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" >> hono.env
echo "export MQTT_ADAPTER_IP=$(kubectl get service eclipse-hono-adapter-mqtt --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" >> hono.env
KAFKA_IP=$(kubectl get service eclipse-hono-kafka-0-external --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)
TRUSTSTORE_PATH=/tmp/truststore.pem
kubectl get secrets eclipse-hono-kafka-example-keys --template="{{index .data \"ca.crt\" | base64decode}}" -n hono > ${TRUSTSTORE_PATH}
echo "export APP_OPTIONS='-H ${KAFKA_IP} -P 9094 -u hono -p hono-secret --ca-file ${TRUSTSTORE_PATH} --disable-hostname-verification'" >> hono.env
echo "export CURL_OPTIONS='--cacert ${TRUSTSTORE_PATH}'" >> hono.env
echo "export MOSQUITTO_OPTIONS='--cafile ${TRUSTSTORE_PATH}'" >> hono.env

yj@DESKTOP-O87AV3J MINGW64 /tmp
$ cat hono.env
export REGISTRY_IP=127.0.0.1
export HTTP_ADAPTER_IP=127.0.0.1
export MQTT_ADAPTER_IP=127.0.0.1
export APP_OPTIONS='-H 127.0.0.1 -P 9094 -u hono -p hono-secret --ca-file /tmp/truststore.pem --disable-hostname-verification'
export CURL_OPTIONS='--cacert /tmp/truststore.pem'
export MOSQUITTO_OPTIONS='--cafile /tmp/truststore.pem'

yj@DESKTOP-O87AV3J MINGW64 /tmp
$ source ~/hono.env

yj@DESKTOP-O87AV3J MINGW64 /tmp
$ curl -i -X POST ${CURL_OPTIONS} -H "content-type: application/json" --data-binary '{
  "ext": {
    "messaging-type": "kafka"
  }
}' https://${REGISTRY_IP}:28443/v1/tenants
curl: (60) schannel: SEC_E_UNTRUSTED_ROOT (0x80090325) - More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

yj@DESKTOP-O87AV3J MINGW64 /tmp

**Comment by yangdaren444** [comment]
在 ubuntu18.04  20,windows10下尝试运行，都是一样问题

**Comment by sophokles73** [comment]
This seems to be related to https://github.com/eclipse/packages/issues/472
Can you try to uninstall Hono and re-install it with the most recent chart (2.4.2)?
Do a

```sh
helm repo update
helm search repo hono
```
to make sure you use the latest 2.4.2 chart.

**Comment by yangdaren444** [comment]
![image](https://github.com/eclipse-hono/hono/assets/139455943/c3178268-e6de-47c4-ad7d-54e931153e9e)

**Comment by yangdaren444** [comment]
ok

**Comment by yangdaren444** [comment]
hono.env
work1@ubuntu:~$ cat hono.env
export REGISTRY_IP=10.110.32.212
export HTTP_ADAPTER_IP=10.107.245.22
export MQTT_ADAPTER_IP=10.109.252.248
export APP_OPTIONS='-H 10.103.129.149 -P 9094 -u hono -p hono-secret --ca-file /tmp/truststore.pem --disable-hostname-verification'
export CURL_OPTIONS='--cacert /tmp/truststore.pem'
export MOSQUITTO_OPTIONS='--cafile /tmp/truststore.pem'
work1@ubuntu:~$ source hono.env
work1@ubuntu:~$ curl -i -X POST ${CURL_OPTIONS} -H "content-type: application/json" --data-binary '{
>   "ext": {
>     "messaging-type": "kafka"
>   }
> }' https://${REGISTRY_IP}:28443/v1/tenants
curl: (60) SSL certificate problem: unable to get issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by yangdaren444** [comment]
ork1@ubuntu:~$ helm list -n hono
NAME        	NAMESPACE	REVISION	UPDATED                                  	STATUS  	CHART     	APP VERSION
eclipse-hono	hono     	1       	2023-07-05 18:35:52.807699628 -0700 -0700	deployed	hono-2.4.2	2.3.0      
work1@ubuntu:~$

**Comment by yangdaren444** [comment]
helm list -n hono


NAME        	NAMESPACE	REVISION	UPDATED                                  	STATUS  	CHART     	APP VERSION
eclipse-hono	hono     	1       	2023-07-05 18:35:52.807699628 -0700 -0700	deployed	hono-2.4.2	2.3.0      
work1@ubuntu:~$

**Comment by yangdaren444** [comment]
Updated, issue still exists

**Comment by sophokles73** [comment]
does `/tmp/truststore.pem` actually exists and contains the ca-certs of your Hono installation?

**Comment by yangdaren444** [comment]
work1@ubuntu:/tmp$ sudo ls  /tmp/t*
[sudo] password for work1: 
/tmp/truststore.pem

/tmp/tmpoo5u5pb3:
apt.conf
work1@ubuntu:/tmp$ 

 actually exists ,

**Comment by yangdaren444** [comment]
echo "export REGISTRY_IP=$(kubectl get service eclipse-hono-service-device-registry-ext --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" > hono.env
echo "export HTTP_ADAPTER_IP=$(kubectl get service eclipse-hono-adapter-http --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" >> hono.env
echo "export MQTT_ADAPTER_IP=$(kubectl get service eclipse-hono-adapter-mqtt --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)" >> hono.env
KAFKA_IP=$(kubectl get service eclipse-hono-kafka-0-external --output="jsonpath={.status.loadBalancer.ingress[0]['hostname','ip']}" -n hono)
TRUSTSTORE_PATH=/tmp/truststore.pem
kubectl get secrets eclipse-hono-kafka-example-keys --template="{{index .data \"ca.crt\" | base64decode}}" -n hono > ${TRUSTSTORE_PATH}
echo "export APP_OPTIONS='-H ${KAFKA_IP} -P 9094 -u hono -p hono-secret --ca-file ${TRUSTSTORE_PATH} --disable-hostname-verification'" >> hono.env
echo "export CURL_OPTIONS='--cacert ${TRUSTSTORE_PATH}'" >> hono.env
echo "export MOSQUITTO_OPTIONS='--cafile ${TRUSTSTORE_PATH}'" >> hono.env


Through this production

**Comment by sophokles73** [comment]
what is the content of `/tmp/truststore.pem`? Do you need root privileges to read it?

**Comment by yangdaren444** [comment]
ork1@ubuntu:~$ cat /tmp/truststore.pem 
-----BEGIN CERTIFICATE-----
MIIB4zCCAYmgAwIBAgIUDvfsevHpF7ObReAAmGXXHHsAXD0wCgYIKoZIzj0EAwIw
UjELMAkGA1UEBhMCQ0ExDzANBgNVBAcMBk90dGF3YTEUMBIGA1UECgwLRWNsaXBz
ZSBJb1QxDTALBgNVBAsMBEhvbm8xDTALBgNVBAMMBHJvb3QwHhcNMjMwNjI0MDkw
NjAwWhcNMjQwNjIzMDkwNjAwWjBQMQswCQYDVQQGEwJDQTEPMA0GA1UEBwwGT3R0
YXdhMRQwEgYDVQQKDAtFY2xpcHNlIElvVDENMAsGA1UECwwESG9ubzELMAkGA1UE
AwwCY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQphoV7ZJZg71VRld66PKiW
MHYatfL71/xughhSsHfe4GYNA6h9pz6Qb0e9h8Kj6tLTFNThvZ0E502oy6e/A5tq
oz8wPTAdBgNVHQ4EFgQUbAyRRCU3YCp7Zq1TbGeW/fagqHEwDwYDVR0TAQH/BAUw
AwEB/zALBgNVHQ8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIhAJaqUu4QSLK3pwCd
NLmrKHol6dXqaKSoFUKYVdASsFsRAiBvX8XHIdRk/AekcDX4AejDg1W5EbvP5r1t
KiEsV1l1Tw==
-----END CERTIFICATE-----
work1@ubuntu:~$ 

no  need

**Comment by yangdaren444** [comment]
cat /tmp/truststore.pem      ok

**Comment by sophokles73** [comment]
Can you try to run the curl command, replacing `${CURL_OPTIONS}` with just `-k`:
```sh
curl -i -X POST -k -H "content-type: application/json" ....
```

**Comment by yangdaren444** [comment]
-k  pass through

**Comment by yangdaren444** [comment]
So it's strange that truststore.pem  is automatically generated by the system and there shouldn't be any issues

**Comment by sophokles73** [comment]
Ok, then can you post the output of
```sh
openssl x509 -in /tmp/truststore.pem -text
```

**Comment by yangdaren444** [comment]
work1@ubuntu:~$ openssl x509 -in /tmp/truststore.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0e:f7:ec:7a:f1:e9:17:b3:9b:45:e0:00:98:65:d7:1c:7b:00:5c:3d
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: C = CA, L = Ottawa, O = Eclipse IoT, OU = Hono, CN = root
        Validity
            Not Before: Jun 24 09:06:00 2023 GMT
            Not After : Jun 23 09:06:00 2024 GMT
        Subject: C = CA, L = Ottawa, O = Eclipse IoT, OU = Hono, CN = ca
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:29:86:85:7b:64:96:60:ef:55:51:95:de:ba:3c:
                    a8:96:30:76:1a:b5:f2:fb:d7:fc:6e:82:18:52:b0:
                    77:de:e0:66:0d:03:a8:7d:a7:3e:90:6f:47:bd:87:
                    c2:a3:ea:d2:d3:14:d4:e1:bd:9d:04:e7:4d:a8:cb:
                    a7:bf:03:9b:6a
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                6C:0C:91:44:25:37:60:2A:7B:66:AD:53:6C:67:96:FD:F6:A0:A8:71
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:96:aa:52:ee:10:48:b2:b7:a7:00:9d:34:b9:
         ab:28:7a:25:e9:d5:ea:68:a4:a8:15:42:98:55:d0:12:b0:5b:
         11:02:20:6f:5f:c5:c7:21:d4:64:fc:07:a4:70:35:f8:01:e8:
         c3:83:55:b9:11:bb:cf:e6:bd:6d:2a:21:2c:57:59:75:4f
-----BEGIN CERTIFICATE-----
MIIB4zCCAYmgAwIBAgIUDvfsevHpF7ObReAAmGXXHHsAXD0wCgYIKoZIzj0EAwIw
UjELMAkGA1UEBhMCQ0ExDzANBgNVBAcMBk90dGF3YTEUMBIGA1UECgwLRWNsaXBz
ZSBJb1QxDTALBgNVBAsMBEhvbm8xDTALBgNVBAMMBHJvb3QwHhcNMjMwNjI0MDkw
NjAwWhcNMjQwNjIzMDkwNjAwWjBQMQswCQYDVQQGEwJDQTEPMA0GA1UEBwwGT3R0
YXdhMRQwEgYDVQQKDAtFY2xpcHNlIElvVDENMAsGA1UECwwESG9ubzELMAkGA1UE
AwwCY2EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQphoV7ZJZg71VRld66PKiW
MHYatfL71/xughhSsHfe4GYNA6h9pz6Qb0e9h8Kj6tLTFNThvZ0E502oy6e/A5tq
oz8wPTAdBgNVHQ4EFgQUbAyRRCU3YCp7Zq1TbGeW/fagqHEwDwYDVR0TAQH/BAUw
AwEB/zALBgNVHQ8EBAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIhAJaqUu4QSLK3pwCd
NLmrKHol6dXqaKSoFUKYVdASsFsRAiBvX8XHIdRk/AekcDX4AejDg1W5EbvP5r1t
KiEsV1l1Tw==
-----END CERTIFICATE-----

**Comment by sophokles73** [comment]
Ok, I think I see the issue. You are running against a local installation of Hono and thus I assume that the value of your `REGISTRY_IP` variable is `127.0.0.1`, right?

If so, can you try to run the curl command with `${REGISTRY_IP}` replaced by `localhost`?

**Comment by yangdaren444** [comment]
work1@ubuntu:~$ cat hono.env
export REGISTRY_IP=10.110.32.212
export HTTP_ADAPTER_IP=10.107.245.22
export MQTT_ADAPTER_IP=10.109.252.248
export APP_OPTIONS='-H 10.103.129.149 -P 9094 -u hono -p hono-secret --ca-file /tmp/truststore.pem --disable-hostname-verification'
export CURL_OPTIONS='--cacert /tmp/truststore.pem'
export MOSQUITTO_OPTIONS='--cafile /tmp/truststore.pem'
work1@ubuntu:~$ openssl x509 -in /tmp/truststore.pem -text


I am a Win10 system, installed with ubuntu18.04 vm, and installed with dokder, minikuber, and hono under the vm

**Comment by yangdaren444** [comment]
*************************************************************
work1@ubuntu:$ cat hono.env
export REGISTRY_IP=10.110.32.212
export HTTP_ADAPTER_IP=10.107.245.22
export MQTT_ADAPTER_IP=10.109.252.248
export APP_OPTIONS='-H 10.103.129.149 -P 9094 -u hono -p hono-secret --ca-file /tmp/truststore.pem --disable-hostname-verification'
export CURL_OPTIONS='--cacert /tmp/truststore.pem'
export MOSQUITTO_OPTIONS='--cafile /tmp/truststore.pem'
work1@ubuntu:$ openssl x509 -in /tmp/truststore.pem -text

***************************

I am a Win10 system, installed with ubuntu18.04 vm, and installed with dokder, minikuber, and hono under the vm

**Comment by sophokles73** [comment]
OK, then this cannot work because the registry's server certificate does not contain the IP address as an *alternative subject name*. Simply use the `-k` switch for all the curl commands

**Comment by yangdaren444** [comment]
###############################################################
work1@ubuntu:~$ cat hono.env
export REGISTRY_IP=10.110.32.212
export HTTP_ADAPTER_IP=10.107.245.22
export MQTT_ADAPTER_IP=10.109.252.248
export APP_OPTIONS='-H 10.103.129.149 -P 9094 -u hono -p hono-secret --ca-file /tmp/truststore.pem --disable-hostname-verification'
export CURL_OPTIONS='--cacert /tmp/truststore.pem'
export MOSQUITTO_OPTIONS='--cafile /tmp/truststore.pem'
work1@ubuntu:~$ source hono.env
work1@ubuntu:~$ curl -i -X POST ${CURL_OPTIONS} -H "content-type: application/json" --data-binary '{
>   "ext": {
>     "messaging-type": "kafka"
>   }
> }' https://${REGISTRY_IP}:28443/v1/tenants
curl: (60) SSL certificate problem: unable to get issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
work1@ubuntu:~$ 
work1@ubuntu:~$ curl -i -X POST ${CURL_OPTIONS} -H "content-type: application/json" --data-binary '{
>   "ext": {
>     "messaging-type": "kafka"
>   }
> }' https://localhost:28443/v1/tenants
curl: (7) Failed to connect to localhost port 28443: Connection refused
work1@ubuntu:~$ 
#######################################################

**Comment by yangdaren444** [comment]
How can the registry's server certificate contain the IP address? I don't want to use - k to handle it, because the example of mqtt also requires certificate verification, which cannot be - k

**Comment by sophokles73** [comment]
The mosquitto client can also be configured to not verify the hostname.
`mosquitto_pub --help` is your friend ...

**Comment by yangdaren444** [comment]
thank you,looked le

**Comment by sophokles73** [comment]
@yangdaren444 can this be closed?
