### ISSUE TITLE
Invalid PVC size

### ISSUE THREAD

**Issue by paulocabrita-ionos** [eclipse-hono/hono#3513]
Hello.

I'm trying to install Hono with the default configuration using the IONOS Cloud without success.

I used the following command  to do the install process:
```
helm install --dependency-update -n digitaltwin-iot eclipse-hono eclipse-iot/hono
```

And I have Dynamic  Volume Provisioning by default but the device registry is always on a pending state. So I did some research and I found the following error:

![image](https://github.com/eclipse-hono/hono/assets/109610228/dcc49740-3840-42e1-a20c-ae11d8e86aa2)

It seems that the size of the storage for the device registry pod is too small and does not comply with the IONOS policy which minimum length is 1Gb.

Is it possible to increase the device registry pod storage size? I didn't find any parameter looking at Hono's chart. Any advice?

I think my issue is related to this one: https://github.com/eclipse-hono/hono/issues/1694

Thanks

**Comment by sophokles73** [comment]
[Please do not upload images of code/data/errors.](//meta.stackoverflow.com/q/285551)

**Comment by sophokles73** [comment]
Please create a corresponding issue in the [Eclipse IoT Packages](https://github.com/eclipse/packages) project, as this seems to be related to the Hono Helm chart, which is being maintained there ...

**Comment by paulocabrita-ionos** [comment]
Done.

Thanks.
