### ISSUE TITLE
Problems with build

### ISSUE THREAD

**Issue by alekseevad** [eclipse-hono/hono#3515]
Can you please tell me how to build your own version of hono with specified data base and run it as a docker containers on a local machine? It wasn't clear for me from Documentation/ Thank you.

**Comment by sophokles73** [comment]
Just follow the [Build instructions](https://eclipse.dev/hono/docs/dev-guide/building_hono/) and the [Deployment Guide](https://eclipse.dev/hono/docs/deployment/)
