### ISSUE TITLE
Enable http insecure port leads to https connection failed

### ISSUE THREAD

**Issue by snowwolf007cn** [eclipse-hono/hono#3525]
I installed hono using helm and enable HTTP adapter insecure port with configuration below:
```yaml
  http:
    hono:
      http:
        insecurePortEnabled: true
        insecurePortBindAddress: 0.0.0.0
```
After installation completed, I test HTTP adapter using Postman. When using the HTTP protocol everything work fine. But after I switched to HTTPS and connected to hono using curl:
```shell
curl --location --request PUT 'https://127.0.0.1:18443/telemetry/7e07519a-623e-4317-822d-93f359f15934/38c08787-f91d-4f62-b356-97d4d9615921' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic MzhjMDg3ODctZjkxZC00ZjYyLWIzNTYtOTdkNGQ5NjE1OTIxQDdlMDc1MTlhLTYyM2UtNDMxNy04MjJkLTkzZjM1OWYxNTkzNDoxMjM0NTY3OA==' \
--data '{
    "tenant_id": "7e07519a-623e-4317-822d-93f359f15934",
    "device_id": "38c08787-f91d-4f62-b356-97d4d9615921",
    "time": "2023-08-07 00:27:25.157",
    "data": {
        "temp-s1":42.4,
        "pressure-s1": 0.022
    }
}'
```
It said:
```
Error: Client network socket disconnected before secure TLS connection was established
```
What's the problem here, and how to fixed it?

**Comment by sophokles73** [comment]
Are you sure you are using the correct port? Are you deploying to a local minikube?

**Comment by sophokles73** [comment]
@snowwolf007cn is this still an issue or can we close this?

**Comment by snowwolf007cn** [comment]
Sorry for missing this issue for quite some time, it's still not working, and I deploying it to a local k3d
