### ISSUE TITLE
Creating new tenant in hono gives timeout error

### ISSUE THREAD

**Issue by BHUVANESHWARI967** [eclipse-hono/hono#3531]
I have installed hono using helm in minikube cluster. All the pods are running successfully,
```
$ kubectl get all -n hono
NAME                                                       READY   STATUS    RESTARTS   AGE
pod/eclipse-hono-adapter-amqp-67f95968d8-6c9sp             1/1     Running   3          26h
pod/eclipse-hono-adapter-http-d48459b97-jzm98              1/1     Running   3          26h
pod/eclipse-hono-adapter-mqtt-674dbb4c54-qjgfk             1/1     Running   3          26h
pod/eclipse-hono-kafka-0                                   1/1     Running   13         26h
pod/eclipse-hono-service-auth-5c86dbdd58-p7r82             1/1     Running   3          26h
pod/eclipse-hono-service-command-router-74d9d6744d-dgqwk   1/1     Running   3          26h
pod/eclipse-hono-service-device-registry-0                 1/1     Running   3          26h
pod/eclipse-hono-zookeeper-0                               1/1     Running   3          26h
```

 When creating a new tenant getting connection timeout error,

```
$ curl -i -X POST http://$REGISTRY_IP:28080/v1/tenants/new_tenant
curl: (28) Failed to connect to 10.105.141.197 port 28080: Connection timed out
```

Is there anything that I have to do additionally?

**Comment by StFS** [comment]
Looks like you're trying to connect to the internal Kubernetes IP address which most likely won't work from your shell.

What is the output from `kubectl get services -n hono`?

In my case I see a line like this:

```
NAME                                       TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
eclipse-hono-service-device-registry-ext   LoadBalancer   10.100.169.159   localhost     28443:30106/TCP                 20h
```

This means that my device registry is running on a pod that has a "cluster-ip" of `10.100.169.159` but that's only accessible from within kubernetes. However I see that the "external-ip" is `localhost` and I see that port `28443` (on `localhost`) is being forwarded to port `30106` (on the pod).

So the correct way for me to access the device registry is to use ` curl -i -X POST https://localhost:28443/v1/...`.

**Comment by BHUVANESHWARI967** [comment]
```
$ kubectl get services -n hono
NAME                                            TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
eclipse-hono-adapter-amqp                       LoadBalancer   10.98.8.80       10.98.8.80       5671:30880/TCP               31h
eclipse-hono-adapter-http                       LoadBalancer   10.105.144.240   10.105.144.240   8443:31911/TCP               31h
eclipse-hono-adapter-mqtt                       LoadBalancer   10.105.141.188   10.105.141.188   8883:30826/TCP               31h
eclipse-hono-kafka                              ClusterIP      10.97.200.199    <none>           9092/TCP,9094/TCP            31h
eclipse-hono-kafka-0-external                   LoadBalancer   10.102.197.50    10.102.197.50    9094:32094/TCP               31h
eclipse-hono-kafka-headless                     ClusterIP      None             <none>           9092/TCP,9093/TCP            31h
eclipse-hono-service-auth                       ClusterIP      10.99.8.247      <none>           5671/TCP,8088/TCP            31h
eclipse-hono-service-command-router             ClusterIP      10.107.15.104    <none>           5671/TCP                     31h
eclipse-hono-service-device-registry            ClusterIP      10.101.181.45    <none>           5671/TCP,8080/TCP,8443/TCP   31h
eclipse-hono-service-device-registry-ext        LoadBalancer   10.105.141.197   10.105.141.197   28443:30151/TCP              31h
eclipse-hono-service-device-registry-headless   ClusterIP      None             <none>           <none>                       31h
eclipse-hono-zookeeper                          ClusterIP      10.108.216.56    <none>           2181/TCP,2888/TCP,3888/TCP   31h
eclipse-hono-zookeeper-headless                 ClusterIP      None             <none>           2181/TCP,2888/TCP,3888/TCP   31h
```

But in my case the internal and external IP are same. Can you tell me what I'm doing wrong here?

**Comment by StFS** [comment]
How are you setting Hono up? And are you deploying to a cluster or a local k8s (docker desktop or k3s or something similar)?

**Comment by BHUVANESHWARI967** [comment]
I have deployed Hono using minikube cluster.

**Comment by sophokles73** [comment]
Have you run `minikube tunnel` before you have installed Hono?

**Comment by BHUVANESHWARI967** [comment]
Yes I did run the minikube tunnel.

**Comment by sophokles73** [comment]
The device registry is listening on port 28443 on IP address 10.105.141.197 in your case. It also uses TLS so you will need to use https to access it.
Then you should be able to reach the registry using something like this
```sh
curl -i -X --insecure POST https://10.105.141.197:28443/v1/tenants/DEFAULT_TENANT
```

The `--insecure` switch will most likely be necessary to omit the hostname verification of the server certificate ...

**Comment by sophokles73** [comment]
@BHUVANESHWARI967 is this still an issue or can we close this?

**Comment by BHUVANESHWARI967** [comment]
@sophokles73 When I'm trying to get pod status,

```
bhu@hono-ditto:~$ kubectl get pods -n hono
Unable to connect to the server: net/http: TLS handshake timeout
```
Can you explain what is causing this problem? Everytime I restart the machine I'm getting this error.

**Comment by BHUVANESHWARI967** [comment]
I was able to resolve that, I have an doubt about making hono connection with ditto(without c2e apckage).

Can we establish a connection between hono which is installed in minikube cluster and the ditto which is installed using docker compose?

**Comment by sophokles73** [comment]
> I was able to resolve that

Ok, I will then close this issue.

If you have another question please open a dedicated issue for that. If it is a question regarding Ditto, please use the [Ditto community channels](https://eclipse.dev/ditto/feedback.html) to ask your question.
