### ISSUE TITLE
Hono Sandbox drop connections

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse-hono/hono#3538]
A week ago this [python script](https://github.com/eclipse-kanto/kanto/raw/main/quickstart/hono_commands.py) worked as expected. It connects to _amqps://hono.eclipseprojects.io:15671_ to wait for a device response. Meanwhile second AMQP connection is created to send a command to a device, which triggers the expected response.

Currently the scripts fails to create the second connection and send the command to the device with `PN_CONNECTION_REMOTE_CLOSE`(The remote endpoint has closed the connection). When I modify the script to make a single connection then the command is successfully send. However this time on the device side the MQTT connection drops with `EOF`.

As there are no changes in both the device code and the python scripts, I assume that there might be some problem with the Hono Sanbox. Maybe it has run out of disk space?

**Comment by sophokles73** [comment]
The Sandbox installation seems to be working fine. What I can see in the log file of the Dispatch Router is that the *connections per host* limit is reached for several of the connection requests. The limit is currently defined at 10 connections per host.

**Comment by dimitar-dimitrow** [comment]
Thanks @sophokles73, this limit seems to be the reason. When the machine is connected to another network, the script run as expected. I will investigate what/who is holding, so many connections on the initial network.

**Comment by sophokles73** [comment]
@dimitar-dimitrow please note that the *host* in your case might be your corporate network's NATed IP address, i.e. all connections from within your network will probably seem to be originating from the same host from the Sandbox' perspective ...

**Comment by dimitar-dimitrow** [comment]
I face a similar problem again, this time I could not create even a single AMQP connection, it gets dropped with `PN_CONNECTION_REMOTE_CLOSE`. I am not behind a corporate network, so I assume that _connections per host_ limit should not be the problem. @sophokles73 do you have an idea, or maybe there is something in the sandbox logs.

**Comment by sophokles73** [comment]
I have been able to connect to the AMQP 1.0 endpoint successfully. I have not seen anything extraordinary in the logs so far. Anyway, I have restarted the cluster and have verified that I can connect to it. Would you mind trying again? If you are still not able to connect, I might have a better chance of seeing something in the logs.

**Comment by dimitar-dimitrow** [comment]
I tried again and now all works as expected, seems as the cluster restart has helped.
