### ISSUE TITLE
Corrupt jdbc connection because of integrated connection pooler (c3p0)

### ISSUE THREAD

**Issue by nupis-DanielS** [eclipse-hono/hono#3539]
Hi,

we use Eclipse Hono (jdbc device registry) in a Kubernetes environment with PostgreSql. When the postgres deployment restarts the now corrupt connection is still being used and is not closed by hono. That leads to an error for the first transaction after the restart.

Is there a possibility to use a new connection for every transaction or to disable the integrated c3p0 connection pool?

![Hono error log](https://github.com/eclipse-hono/hono/assets/66111132/315f00ed-fd02-44b9-b524-34c92e2bdbb2)

**Comment by sophokles73** [comment]
@mattkaem any thoughts?

**Comment by sophokles73** [comment]
I believe that https://www.mchange.com/projects/c3p0/#configuring_connection_testing could provide some insights. I am not sure, though, if Hono currently uses connection checking but it looks like this could already be the solution to the problem.

**Comment by mattkaem** [comment]
I think currently we do not check the status of a connection before using it but, looking at the documentation of c3p0, it seems there is a way to do so (https://www.mchange.com/projects/c3p0/#configuring_connection_testing).
To my knowledge it is currently not possible to disable the connection pool or to have a new connection for every transaction.

**Comment by sophokles73** [comment]
@nupis-DanielS would you like to give adding support for enabling connection checking a shot?

@mattkaem and I can support if necessary

**Comment by nupis-DanielS** [comment]
Sure, i will give it a try ;-)

**Comment by harism** [comment]
Switching to Quarkus Agroal datasource can also make a difference [#3562] and harden it connections are dropped from the pool.

**Comment by sophokles73** [comment]
@nupis-DanielS with #3562 having been merged, is this still an issue?

**Comment by nupis-DanielS** [comment]
Hi,

thank you for your development. Is there a possiblity to get a pre relase image of the version 2.5.0. We can only reproduce it in our cluster which uses the hono helm chart.

**Comment by nupis-DanielS** [comment]
We updated the hono to version 2.5.0 and it looks good. No bad connections so far.

thanks :-)
