### ISSUE TITLE
Add configuration parameters for JDBC connection pool

### ISSUE THREAD

**Issue by mattkaem** [eclipse-hono/hono#3542]
Currently, the only configuration that can be done for the JDBC connection pool, besides the connection to the database of course, is the maximum number of connections. I would like to enhance this with configuration parameters for the minimum number of connections, the initial number of connections and the maximum idle timeout.

**Comment by mattkaem** [comment]
I would say so, yes. It is the same connections pool that has to be altered.

**Comment by sophokles73** [comment]
Well, that I understood. The question is more: will your activities also address the issue raised in #3539?

**Comment by mattkaem** [comment]
No this will not address https://github.com/eclipse-hono/hono/issues/3539

**Comment by sophokles73** [comment]
Looking forward to the PR :-)
