### ISSUE TITLE
Commands on the internal command subscription are not acknowledged properly if Pub/Sub is used as the messaging infrastructure

### ISSUE THREAD

**Issue by mattkaem** [eclipse-hono/hono#3543]
When we use Pub/Sub as a messaging infrastructure, we currently process command messages from the internal command subscription without acknowledging them. This can lead to problems with processing new commands if the number of unacknowledged messages within the subscription grows to large. I suggest we acknowledge a command once we start processing it in the responsible adapter instance.

**Comment by sophokles73** [comment]
> we currently process command messages from the internal command subscription without acknowledging them

Do you *never* acknowledge messages or just don't ack messages that cannot be delivered to devices?

**Comment by mattkaem** [comment]
We never acknowledge the messages.

**Comment by sophokles73** [comment]
Shouldn't you then eventually run into this problem also in case all messages are getting delivered successfully?

**Comment by mattkaem** [comment]
> Shouldn't you then eventually run into this problem also in case all messages are getting delivered successfully?

yes, definitively we do.

**Comment by sophokles73** [comment]
@mattkaem I believe that this affects 2.4.x as well, right? If so, can you please also add the fix to the 2.4.x branch?

**Comment by mattkaem** [comment]
> @mattkaem I believe that this affects 2.4.x as well, right? If so, can you please also add the fix to the 2.4.x branch?

sure, no problem
