### ISSUE TITLE
Migrate device registry to use Quarkus JDBC implementation

### ISSUE THREAD

**Issue by harism** [eclipse-hono/hono#3562]
In the issue [#3555] comment https://github.com/eclipse-hono/hono/issues/3555#issuecomment-1746479695 it was mentioned that using Quarkus JDBC layer on device registry could be beneficial for Hono database communication. And also possibly make it possible H2 works in native executable build too. For these reasons creating this separate issue to track work towards Quarkus JDBC based database communication implementation.

**Comment by harism** [comment]
Oh boy, all these tries to be Vert.x compliant with an own SQL provider, just to realise it today Vert.x has support out-of-the-box for Quarkus Agroal data source. Well finally the integration tests pass too at least.

**Comment by sophokles73** [comment]
closed via #3563
