### ISSUE TITLE
MQTT Adapter - no such endpoint

### ISSUE THREAD

**Issue by paulocabrita-ionos** [eclipse-hono/hono#3567]
Hi everyone.

I'm doing some tests using HONO + DITTO and I'm having an issue when using to different protocols to do the same thing. I'm following the [C2E Tour](https://www.eclipse.org/packages/packages/cloud2edge/tour/l) and following the instructions. 

My goal:
- creation of a Digital Twin (DT) and sending data to the DT using HTTP and MQTT;

What I have done:
- Creation of a new Tenant, an authentication and a DT;
- Sent data to the DT using Hono HTTP adapter (works fine) like this:
```
curl -i -k -u my-auth-id-1@org.skynet:my-password -H 'Content-Type: application/json' --data-binary '{
  "topic": "org.skynet/mycobot1/things/twin/commands/modify",
  "headers": {},
  "path": "/attributes",
  "value": {"joint1":45,"joint2":0.0,"joint3":0.0,"joint4":0.0,"joint5":0.0,"joint6":0.0,"power":false,"longitude":0,"latitude":0,"local":"XPTO"}
}' ${HTTP_ADAPTER_BASE_URL:?}/telemetry
```
- For the Hono MQTT adapter I created a python script based on this [one](https://github.com/eclipse-ditto/ditto-examples/blob/master/mqtt-iwatch-wot/iwatch/send_data_iwatch.py). I want to send a Ditto message so I don't have to create mapping functions on the Ditto side. This is the payload:
```
ditto_data = {
        "topic": "org.skynet/mycobot1/things/twin/commands/modify",
        "path": "/attributes",
        "value":{
              "joint1":1,
              "joint2":2,
              "joint3":3,
              "joint4":4,
              "joint5":5,
              "power":False,
              "longitude":30,
              "latitude":40,
              "local":"XPTO"
            }
    }  
```
- The authentication is OK and the payload is sent but Hono MQTT adapter gives me the following execption:
```
2023-10-10 11:11:23,734 INFO  [org.ecl.hon.ada.mon.LoggingConnectionEventProducer] (vert.x-eventloop-thread-1)    Connected - ID: 135c16b7-a94f-4d9f-a759-48a6ca6d4a18, Protocol Adapter: hono-mqtt, Device: device [device-id: org.skynet:mycobot1, tenant-id: org.skynet], Data: null │
│ 2023-10-10 11:11:24,592 DEBUG [org.ecl.hon.ada.mqt.imp.VertxBasedMqttProtocolAdapter] (vert.x-eventloop-thread-1) no such endpoint [UNKNOWN]                                                                                                     │
│ 2023-10-10 11:11:24,592 DEBUG [org.ecl.hon.ada.mqt.imp.VertxBasedMqttProtocolAdapter] (vert.x-eventloop-thread-1) discarding message [topic: org.skynet:mycobot1/things/twin/commands/modify, authenticated device: device [device-id: org.skynet:mycobot1, tenant-id: org.skynet]]: org.eclipse.hono.client.ClientErrorException: no such endpoint │
│     at org.eclipse.hono.adapter.mqtt.impl.VertxBasedMqttProtocolAdapter.checkQosAndMapTopic(VertxBasedMqttProtocolAdapter.java:160)
```

My thoughts:
- I think that Hono MQTT adapter when it received the packet builds the topic name using the device-id and does not consider the `topic`field of the payload (org.skynet:mycobot1/things/twin/commands/modify vs org.skynet/mycobot1/things/twin/commands/modify). 
- The way I see it, having the same payload for MQTT and HTTP, it should work the same. But maybe I'm missing something here :)

Any thoughts?

**Comment by sophokles73** [comment]
@paulocabrita-ionos can this be closed?

**Comment by paulocabrita-ionos** [comment]
@sophokles73 thanks for the support.

Closing.
