### ISSUE TITLE
Sending data on custom topic on Kafka or MQTT

### ISSUE THREAD

**Issue by PriyankaSwami12** [eclipse-hono/hono#3600]
I am using hono for one of my project. I have deployed MQTT-adapter, Registry-Server and Kafka through helm.

Currently I am able to send data successfully on Kafka on "telemetry" topic. I want to send data on my custom topic, for example: 
"telemetry/<VIN_VALUE>/<CUSTOM_PARAMETER>". I am publishing data using the below code which works for "telemetry" topic, but **NOT** for custom topic.

```
from paho.mqtt.publish import single

def publish():

    payload = "test-data"

    try:
        single(client_id="sender-client", keepalive=5, topic="telemetry/<VIN_VALUE>/<CUSTOM_PARAMETER>",
               payload=payload, qos=1, retain=False, hostname="hono-adapter-mqtt.dev.iat.conmob.cloud",
               auth={"username": 'bbcd2839-c5cf-47c4-866b-4a1e5565099f@83f6110a-efec-43f7-b7be-6c9f71de2fe8',
                     "password": "default-pwd"})

        print(f"Message published")

    except Exception as e:
        print("Exception occurred: " + str(e))

if __name__ == '__main__':
    publish()
    print("published successfully")

```

**Is it possible to create custom topic on Kafka or MQTT? If yes, then can we send data on this custom topic(for example: "telemetry/<VIN_VALUE>/<CUSTOM_PARAMETER>")?**

**Comment by sophokles73** [comment]
No, sorry, this is not possible.
