### ISSUE TITLE
Issue: Fail installation locally hono

### ISSUE THREAD

**Issue by AntonioPerezBazuelo** [eclipse-hono/hono#3601]
Hello everyone,

I'm trying to install Hono locally in my computer (MacOS, Chip Apple M1 Pro, Memory 16 Gb, Ventura 13.6.3).
The steps that I've followed so far are the following:

```
minikube start --memory=8g --cpus=4
kubectl create namespace hono
helm repo add eclipse-iot https://eclipse.org/packages/charts
helm repo update
minikube addons enable metrics-server
minikube addons enable ingress
minikube tunnel
```
and in a new terminal

`helm install eclipse-hono eclipse-iot/hono -n hono --wait`

However, the installation does not reach the end and it returns "Error: INSTALLATION FAILED: context deadline exceeded
"

I'm using minikube v1.32.0 inside Darwin 13.6.3 (arm64), I'm creating the docker container with 4 cpus and 8 GB of memory. The kubernetes version is 1.28.3 and the Docker version is 24.0.7. I've also tried to increase the memory

I'm kinda stuck here and I don't really find where is the issue...

Thank you very much for your help

**Comment by sophokles73** [comment]
This seems to be related to the Helm chart which is maintained in the [Eclipse Packages project](https://github.com/eclipse/packages). Please post your questions/issues related to the Helm chart there. This repository is only used to maintain the Hono code itself. Thanks.
