### ISSUE TITLE
Hono device registry JDBC native image 2.5.0 missing

### ISSUE THREAD

**Issue by harism** [eclipse-hono/hono#3604]
In relation to closed issue #3555 --

Now that the JDBC device registry native build has been executing as part of native integration tests, would it be ok to add it to published native images also;
[hono/push_hono_images.sh](https://github.com/eclipse-hono/hono/blob/6ca06336f7484aa117005d62cd20a3bf380a6a9e/push_hono_images.sh#L38)

Line 38 in [6ca0633](https://github.com/eclipse-hono/hono/commit/6ca06336f7484aa117005d62cd20a3bf380a6a9e)

         hono-service-device-registry-mongodb-native" 
Currently this image 2.5.0 version is still missing from Docker Hub, and I didn't think of this while making the functional changes.

**Comment by sophokles73** [comment]
I had noticed as well when I pushed the images last night ;-)
Firts, we had to have the Eclipse Foundation create the corresponding Docker Hub repository for the image. Now we can push the image.

Feel free to create a corresponding PR ... :+1:

**Comment by harism** [comment]
I am not 100% sure how I should have handled it to make same change in master and 2.5.x branches and I can change this if the current 2 PRs one for each branch is not the wanted way.

**Comment by sophokles73** [comment]
closed via #3606 and #3607
