### ISSUE TITLE
Ways to include LwM2M protocol custom support in HONO

### ISSUE THREAD

**Issue by mhatrepratik11** [eclipse-hono/hono#3614]
**Hello Team.**

I am using HONO and implemented MQTT adapter with Kafka which is working very fine. Further, I want to use LwM2M adapter in HONO. As LwM2M is not supported in HONO directly, I am trying to find a custom way to do it.

**I had gone through some links where I got some suggestions:**
1)  To put the Leshan server as bridge between the devices and HONO server:
     In this case 2 questions arises —>
     Q1) **Leshan server as bridge:** Does that mean, I will create a java based application taking reference of Leshan
          implementation which will act as Leshan server which takes LwM2M message from device and then converts it to MQTT message and
          sends it to MQTT adapter in HONO and vice versa. Rest of the process remains same. Is this the correct approach?
     Q2) I have availed the X509 certificate based authentication with MQTT, In this case I will receive the client certificate from
          device to LWM2M java application then should I supposed to send these certificates to MQTT for authentication? If yes, Is
          this a correct way to do it?

2)  I have gone through this link [https://eclipse.dev/hono/docs/dev-guide/custom_http_adapter](url) where I got to know we can
      create a custom adapter which supports LWM2M in Hono. Are there any other reference available or any other examples which
      are more elaborative.

**Comment by sophokles73** [comment]
ad Q1) Yes, in general that is what you would need to do. However, I would recommend to connect to Hon's AMQP adapter instead of the MQTT adapter because it supports back pressure and message properties.
ad Q2) No your bridge will do the client authentication and will vouch for the device identity towards Honor. Your bridge will itself authenticate to the AMQP adapter using any of the supported mechanisms.

ad 2) The example you refer to is for a custom protocol adapter, not a bridge. But no, there is no other example available.

**Comment by mhatrepratik11** [comment]
Thank you for your reply @sophokles73.

Just last question and we are good to close this issue. Can't we send LwM2M request to HONO through CoAP? In other words can we make use of CoAP adapter in HONO to send and accept LwM2M request and response?

Thanks in Advance !

**Comment by sophokles73** [comment]
In theory, that seems possible (and I have been going down that rabbit hole for some time). Some features of LwM2M map quite well to Hono but when it comes to subscriptions, things get problematic because of the distributed nature of Hono protocol adapters.

**Comment by mhatrepratik11** [comment]
Thank you for clarification @sophokles73. Will not go that way then as it does not work well with subscriptions. Thanks again and closing this issue.
