### ISSUE TITLE
Error: resource version mismatch 

### ISSUE THREAD

**Issue by srinivaschannakeshava** [eclipse-hono/hono#3640]
I am trying to run HONO and executing some of the api's . How ever I am receving error version mismatch exception on trying to update both on tenants and device api's . What am i missing/doing wrong here - can you please help?
Below is the stack trace.

`hono-device-registry-jdbc-1  | 2024-05-31 14:03:36,121 DEBUG [org.ecl.hon.ser.man.ten.DelegatingTenantManagementHttpEndpoint] (vert.x-eventloop-thread-5) updating tenant [MQTT_TENANT]
hono-device-registry-jdbc-1  | 2024-05-31 14:03:36,123 DEBUG [org.ecl.hon.ser.bas.jdb.sto.ten.ManagementStore] (vert.x-eventloop-thread-5) update - statement: ExpandedStatement{sql=UPDATE tenants
hono-device-registry-jdbc-1  | SET
hono-device-registry-jdbc-1  |    data=?,
hono-device-registry-jdbc-1  |    version=?
hono-device-registry-jdbc-1  | WHERE
hono-device-registry-jdbc-1  |    tenant_id=?
hono-device-registry-jdbc-1  | AND
hono-device-registry-jdbc-1  |    version=?
hono-device-registry-jdbc-1  | , parameters=[{"enabled":false}, d48956f7-50c5-4718-b9a8-ff0e8c52e850, MQTT_TENANT, do Ut]}
hono-device-registry-jdbc-1  | 2024-05-31 14:03:36,145 DEBUG [org.ecl.hon.ser.man.ten.DelegatingTenantManagementHttpEndpoint] (vert.x-eventloop-thread-5) error processing request: org.eclipse.hono.client.ClientErrorException: resource version mismatch
hono-device-registry-jdbc-1  |  at org.eclipse.hono.deviceregistry.jdbc.impl.Services.recover(Services.java:61)
hono-device-registry-jdbc-1  |  at org.eclipse.hono.deviceregistry.jdbc.impl.TenantManagementServiceImpl.lambda$processUpdateTenant$6(TenantManagementServiceImpl.java:110)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition.onFailure(Composition.java:50)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FixedMapping.onFailure(FixedMapping.java:36)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:268)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:43)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:262)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FixedMapping.onSuccess(FixedMapping.java:31)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
hono-device-registry-jdbc-1  |  at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
hono-device-registry-jdbc-1  |  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
hono-device-registry-jdbc-1  |  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
hono-device-registry-jdbc-1  |  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
hono-device-registry-jdbc-1  |  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
hono-device-registry-jdbc-1  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
hono-device-registry-jdbc-1  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
hono-device-registry-jdbc-1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
hono-device-registry-jdbc-1  |  at java.base/java.lang.Thread.run(Unknown Source)
hono-device-registry-jdbc-1  | 
hono-device-registry-jdbc-1  | 2024-05-31 14:03:36,146 DEBUG [org.ecl.hon.ser.htt.DefaultFailureHandler] (vert.x-eventloop-thread-5) handling failed route for request [method: PUT, URI: http://127.0.0.1:7080/v1/tenants/MQTT_TENANT, status: 412]; error: org.eclipse.hono.client.ClientErrorException: resource version mismatch`

**Comment by calohmn** [comment]
@srinivaschannakeshava According to the logs, you have set the `If-Match` HTTP header with value `do Ut` in your `PUT http://127.0.0.1:7080/v1/tenants/MQTT_TENANT` request. This is an _optional_ header containing the expected resource version of the tenant to be updated (as returned in the `etag` HTTP header in the tenant GET response). The given header in your case doesn't match the resource version of the tenant, hence the error.

If you want to update the tenant without any resource version check, just leave out the `If-Match` HTTP header.

PS: The stacktrace above would be much more readable if you put it in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (using triple backticks). Then the line-breaks don't get removed.

**Comment by srinivaschannakeshava** [comment]
@calohmn  Thank you for the quick reply - Its working now, is there any place where this insights are captured?

Also I am trying to set the entire project - is there any developer/contributor guide that can be shared . I am stuck at running the project in my Eclipse IDE.
