### ISSUE TITLE
Hono Sandbox: ERROR:proton:connection disallowed by local policy

### ISSUE THREAD

**Issue by k-gostev** [eclipse-hono/hono#3642]
I am using the Hono sandbox.
When I try to run [this script](https://github.com/eclipse-kanto/kanto/blob/main/quickstart/hono_commands.py), following [this how-to guide](https://eclipse.dev/kanto/docs/getting-started/hono/) I receive an error: `ERROR:proton:connection disallowed by local policy` or occasionally `Connection Error PN_CONNECTION_REMOTE_CLOSE(<proton._endpoints.Connection 0xf2767ff6dc00 ~ 0xf27678000fe0>)`

Am I exceeding some thresholds , or  are there any recent changes made to the sandbox  that would require to adapt the existing scripts?

**Comment by sophokles73** [comment]
I'll take a look at the Sandbox logs ...

**Comment by sophokles73** [comment]
It looks like you have too many (i.e. > 10) connections opened from your host, or the network behind your organization's NAT router ...

```
2024-06-05 10:16:32.317727 +0000 POLICY (info) DENY AMQP Open for user 'consumer@HONO', rhost '10.42.0.1', vhost 'hono': Connection denied by application per host limit
```

**Comment by k-gostev** [comment]
Thanks a lot @sophokles73, for checking it out!

**Comment by k-gostev** [comment]
Error `ERROR:proton:connection disallowed by local policy` could be seen, even when I run the scripts in an EC2 instance in AWS, so I don't think it would be the organisation's network at fault. Do you have other suggestions?

**Comment by sophokles73** [comment]
Can you provide a timestamp and/or log entry for the failed connection attempt so that I can try to correlate it with the Sandbox logs?

**Comment by sophokles73** [comment]
Ok, it seems that the Dispatch Router is actually behind a reverse proxy that makes _all_ incoming connections appear to be coming from the same host, regardless of where they are really originating from. The limit is set to 10 which seems to be already reached. I can increase that limit but that will not guarantee a _free slot_ at all times because I do not know, who is creating (and keeping) all of these connections in the first place.

**Comment by sophokles73** [comment]
I have to reboot the Sandbox now in order to apply some patches. I will also increase the connection limit. Let's see if this resolves the issue (for now) ...

**Comment by sophokles73** [comment]
@k-gostev can this be closed?

**Comment by k-gostev** [comment]
@sophokles73, thanks a lot for the support! Our how-to guides are working as expected now
