### ISSUE TITLE
Prometheus based resource limit check is hardcoded to use port 9090 only

### ISSUE THREAD

**Issue by harism** [eclipse-hono/hono#3647]
Unless I'm mistaken this single line;
https://github.com/eclipse-hono/hono/blob/6a05ee38ea9f7ad98e0c15b0e6f3ce40963abb6b/adapter-base/src/main/java/org/eclipse/hono/adapter/resourcelimits/PrometheusBasedResourceLimitChecksConfig.java#L71

Causes it that the documented configurable Prometheus port variable is always overrode with this `9090` value, and the configuration variable `hono.resourceLimits.prometheusBased.port` coming in the `PrometheusBasedResourceLimitCheckOptions` constructor parameter has no effect.

**Comment by sophokles73** [comment]
I guess you are right.

**Comment by sophokles73** [comment]
Fixed via #3648
