### ISSUE TITLE
Add optional message tracing logs for CoAP adapter

### ISSUE THREAD

**Issue by harism** [eclipse-hono/hono#3656]
Shortly the idea is, which I'm willing to implement if agreed so;
1. Add a configuration flag to enable CoAP message tracing logs in CoAP adapter - false by default
2. Add Californium default [MessageTracer](https://javadoc.io/doc/org.eclipse.californium/californium-core/3.11.0/org/eclipse/californium/core/network/interceptors/MessageTracer.html) interceptor in the code to use based on the flag setting

Enabling this flag will add INFO level logs from default MessageTracer which look similar to this example;
```
UDP(10.244.3.155:55816) ==> req CON-PUT    MID=43112, Token=C813, OptionSet={"Uri-Path":["t","test"]}, FC 00 <-- payload
```

Purpose is to see message details especially in situations where they do not map into uri-paths which Hono implements and in these rare cases can be difficult to understand why the message doesn't even reach to Hono and Californium discards it already.

Usually that would mean that the client does not follow CoAP specification closely enough, and this flag is kind of a debug mode where every message gets logged with details it carries.

However there is always the security aspect to consider too with this kind of features.

**Comment by sophokles73** [comment]
Sounds reasonable. The only caveat I see is that we should not include the payload in the logs ...

**Comment by harism** [comment]
Do you mean that payload should not be logged at all or are you worried about the length instead?

In case of the length this default MessageTracer use seems to limit payload output to [max 32 characters](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/coap/Message.java#L646) long.

**Comment by sophokles73** [comment]
Can this be closed or do you want to do additional work on the documentation?
Also, FMPOV it would be good to be required to explicitly enable logging of payload for privacy/security.

**Comment by harism** [comment]
> Can this be closed or do you want to do additional work on the documentation? Also, FMPOV it would be good to be required to explicitly enable logging of payload for privacy/security.

Thinking of this you are correct, there is no interest in the payload anyway as the intention for this logging was from the beginning. Seeing the request arrives and that it uses correct request type and path are the most important details to see if there is communication issues with a device.

I write simple extension for the default Californium message interceptor logger to hide payloads.

**Comment by harism** [comment]
As noted in the PR comments, this feature exists already in a form that suffices. And Californium does log those failed requests on a feasible level to see the request has arrived at least.

**Comment by harism** [comment]
Oh yes most definitely, I need to revert those changes too. Sorry about this hasty closing.
