### ISSUE TITLE
System dashboard - collect unauthorized access to protocol adapters 

### ISSUE THREAD

**Issue by sysexcontrol** [eclipse-hono/hono#366]
Since we now have the integration of credentials with the protocol adapters to prevent unauthorized access to Hono, we should collect the number of failed access attempts as part of the (currently not existing) system dashboard (see #354 ).

In a first step this should just count the number of failed access, but differentiated per protocol adapter.
No special detection algorithms need to be introduced to differentiate between a "currently wrong configured device" from brute force attacks or from credentials that "just" expired.

**Comment by ctron** [comment]
I think it would be a good idea to wait that until PR #809 is merged. Otherwise this will create conflicts.

**Comment by sophokles73** [comment]
This has been added in 1.4.0
